// ============================================================
// 选菜软件 — 菜谱数据库
// ============================================================

// ---- 元素标签 (36个) ----
const ELEMENTS = {
  spring:    { name: "春鲜",     desc: "春天的鲜嫩食材" },
  summer:    { name: "夏爽",     desc: "夏日清爽解暑" },
  autumn:    { name: "秋浓",     desc: "秋日浓郁醇厚" },
  winter:    { name: "冬暖",     desc: "冬天温暖滋补" },
  spicy:     { name: "麻辣",     desc: "花椒辣椒的热烈" },
  sourSweet: { name: "酸甜",     desc: "糖醋果香的平衡" },
  light:     { name: "清淡",     desc: "食材本味至上" },
  rich:      { name: "浓郁",     desc: "酱汁饱满滋味厚" },
  umami:     { name: "鲜香",     desc: "食材天然的鲜美" },
  garlic:    { name: "蒜香",     desc: "蒜的霸道香气" },
  sauce:     { name: "酱香",     desc: "酱油豆瓣发酵香" },
  bamboo:    { name: "笋韵",     desc: "竹笋的脆嫩清甜" },
  mushroom:  { name: "菌菇",     desc: "各类菌子的山野味" },
  seafood:   { name: "海鲜",     desc: "鱼虾蟹贝的鲜" },
  riverFood: { name: "河鲜",     desc: "淡水鱼虾的细腻" },
  tofu:      { name: "豆韵",     desc: "豆腐豆制品的绵柔" },
  root:      { name: "根茎",     desc: "土豆萝卜山药藕" },
  leafy:     { name: "绿叶",     desc: "青菜时蔬的清新" },
  melon:     { name: "瓜果",     desc: "瓜类水果入菜" },
  poultry:   { name: "禽肉",     desc: "鸡鸭鸽的嫩滑" },
  pork:      { name: "猪肉",     desc: "猪肉的百变风情" },
  beefLamb:  { name: "牛羊",     desc: "牛羊肉的厚实" },
  egg:       { name: "蛋香",     desc: "鸡蛋的朴素温暖" },
  tropical:  { name: "热带风",   desc: "菠萝芒果椰香" },
  fermented: { name: "发酵味",   desc: "泡菜酸菜豆豉" },
  smoked:    { name: "烟熏",     desc: "腊味熏制的醇厚" },
  pickled:   { name: "腌腊",     desc: "时间沉淀的风味" },
  stirFry:   { name: "爆炒",     desc: "大火快炒的镬气" },
  slowCook:  { name: "慢炖",     desc: "文火久炖的温柔" },
  steam:     { name: "清蒸",     desc: "蒸汽锁住的鲜美" },
  braise:    { name: "红烧",     desc: "酱色浓郁的炖煮" },
  cold:      { name: "凉拌",     desc: "爽口开胃的冷菜" },
  grill:     { name: "煎烤",     desc: "焦香四溢的美味" },
  dryPot:    { name: "干锅",     desc: "干香麻辣的过瘾" },
  boil:      { name: "水煮",     desc: "滚烫热油的鲜嫩" },
  blanch:    { name: "白灼",     desc: "极简烹饪的原味" },
  coolDown:  { name: "解暑",     desc: "清热消暑的凉意" },
  warmUp:    { name: "暖身",     desc: "驱寒暖胃的热乎" },
  moisten:   { name: "润燥",     desc: "秋日滋阴润肺" },
  revive:    { name: "生发",     desc: "春日生发的鲜嫩" },
  zingy:     { name: "鲜辣",     desc: "鲜香与辣味的碰撞" },
};

// ---- 情景词 (60个) ----
const SCENARIO_WORDS = [
  { id: 1,  word: "雨后春笋",   desc: "春雨过后，万物破土而出",           elements: ["spring","bamboo","light","umami","stirFry"] },
  { id: 2,  word: "热带雨林",   desc: "浓绿深处藏着热烈的甜蜜",           elements: ["tropical","sourSweet","melon","summer","grill"] },
  { id: 3,  word: "秋日私语",   desc: "落叶与桂花，低语秋天的秘密",       elements: ["autumn","rich","mushroom","slowCook","moisten"] },
  { id: 4,  word: "江南烟雨",   desc: "小桥流水，湿润的青石板路",         elements: ["light","riverFood","steam","blanch","spring"] },
  { id: 5,  word: "雪山来客",   desc: "高处的风，带着清冽的寒意",         elements: ["winter","beefLamb","slowCook","rich","smoked"] },
  { id: 6,  word: "竹林深处",   desc: "风吹竹叶沙沙，山野间的宁静",       elements: ["bamboo","mushroom","light","steam","spring"] },
  { id: 7,  word: "海风习习",   desc: "咸咸的海风，浪花拍打礁石",         elements: ["seafood","light","blanch","summer","steam"] },
  { id: 8,  word: "夏日炎炎",   desc: "蝉鸣不止，需要一场味觉暴雨",       elements: ["summer","spicy","cold","melon","stirFry"] },
  { id: 9,  word: "金秋送爽",   desc: "稻穗低头，丰收的好时节",           elements: ["autumn","rich","mushroom","pork","braise"] },
  { id: 10, word: "春暖花开",   desc: "万物复苏，味蕾也跟着醒来",         elements: ["spring","leafy","light","egg","stirFry"] },
  { id: 11, word: "冰天雪地",   desc: "窗外飘雪，屋内暖锅沸腾",           elements: ["winter","beefLamb","slowCook","rich","dryPot"] },
  { id: 12, word: "山间清风",   desc: "走出城市，山野食材的召唤",         elements: ["mushroom","bamboo","leafy","light","steam"] },
  { id: 13, word: "暮色晚钟",   desc: "黄昏时分，一天的疲惫需要抚慰",     elements: ["slowCook","rich","pork","autumn","sauce"] },
  { id: 14, word: "晨露微光",   desc: "清晨第一缕阳光，轻盈的开始",       elements: ["light","egg","leafy","spring","steam"] },
  { id: 15, word: "田野漫步",   desc: "踩在泥土上，摘一把新鲜蔬菜",       elements: ["leafy","root","light","garlic","stirFry"] },
  { id: 16, word: "热情似火",   desc: "就是要辣得过瘾，吃得痛快",         elements: ["spicy","dryPot","boil","pork","poultry"] },
  { id: 17, word: "温柔时光",   desc: "慢下来的日子，细嚼慢咽的幸福",     elements: ["slowCook","light","tofu","steam","autumn"] },
  { id: 18, word: "任性一回",   desc: "不管了，今天就要放纵吃",           elements: ["rich","pork","braise","grill","beefLamb"] },
  { id: 19, word: "小确幸",     desc: "微小但确定的幸福，就在一顿饭里",   elements: ["egg","poultry","light","umami","stirFry"] },
  { id: 20, word: "心满意足",   desc: "吃到好吃的，整个人都好了",         elements: ["rich","pork","braise","sauce","autumn"] },
  { id: 21, word: "元气满满",   desc: "能量充满，迎接新的一天",           elements: ["egg","poultry","leafy","garlic","stirFry"] },
  { id: 22, word: "懒洋洋",     desc: "不想动脑子，但也不能亏待胃",       elements: ["slowCook","sauce","pork","root","rich"] },
  { id: 23, word: "甜蜜蜜",     desc: "生活需要一点甜来调味",             elements: ["sourSweet","melon","tropical","grill","pork"] },
  { id: 24, word: "麻辣诱惑",   desc: "嘴唇发麻，额头冒汗，停不下来",     elements: ["spicy","boil","dryPot","beefLamb","poultry"] },
  { id: 25, word: "清爽一下",   desc: "给肠胃放个假，轻盈无负担",         elements: ["light","leafy","tofu","cold","blanch"] },
  { id: 26, word: "江湖夜雨",   desc: "大碗喝酒大口吃肉的豪情",           elements: ["spicy","dryPot","beefLamb","grill","rich"] },
  { id: 27, word: "小桥流水",   desc: "江南水乡的温柔滋味",               elements: ["riverFood","light","steam","tofu","spring"] },
  { id: 28, word: "炊烟袅袅",   desc: "傍晚时分，家家户户飘出饭香",       elements: ["pork","stirFry","sauce","garlic","rich"] },
  { id: 29, word: "灯火阑珊",   desc: "城市的夜，食物是温暖的坐标",       elements: ["grill","spicy","dryPot","poultry","rich"] },
  { id: 30, word: "桃花源记",   desc: "世外桃源，自给自足的田园味",       elements: ["leafy","root","tofu","light","steam"] },
  { id: 31, word: "故人相逢",   desc: "老朋友见面，一桌好菜叙旧情",       elements: ["pork","braise","sauce","rich","slowCook"] },
  { id: 32, word: "围炉夜话",   desc: "围着火炉，边吃边聊到深夜",         elements: ["winter","slowCook","beefLamb","rich","dryPot"] },
  { id: 33, word: "人间有味",   desc: "人间烟火气，最抚凡人心",           elements: ["pork","stirFry","garlic","sauce","sourSweet"] },
  { id: 34, word: "满汉全席",   desc: "今天奢侈一把，多做几个硬菜",       elements: ["seafood","beefLamb","pork","rich","braise"] },
  { id: 35, word: "家常便饭",   desc: "就是家里那个味道，平平淡淡才是真", elements: ["pork","egg","leafy","stirFry","garlic"] },
  { id: 36, word: "阳光明媚",   desc: "天气好心情好，吃饭也要亮堂堂",     elements: ["light","sourSweet","melon","poultry","summer"] },
  { id: 37, word: "和风细雨",   desc: "温柔的一天，清淡温润正好",         elements: ["light","steam","tofu","leafy","spring"] },
  { id: 38, word: "薄雾清晨",   desc: "晨雾未散，一碗热汤暖胃",           elements: ["egg","light","steam","spring","slowCook"] },
  { id: 39, word: "落日余晖",   desc: "黄昏的光，配一桌丰盛晚餐",         elements: ["grill","rich","pork","autumn","zingy"] },
  { id: 40, word: "月下独酌",   desc: "一个人的晚餐，也要有仪式感",       elements: ["light","riverFood","steam","tofu","cold"] },
  { id: 41, word: "烟火人间",   desc: "市井街头的热闹，都在锅里沸腾",     elements: ["spicy","stirFry","dryPot","pork","garlic"] },
  { id: 42, word: "周末慵懒",   desc: "睡到自然醒，慢悠悠做顿饭",         elements: ["slowCook","sauce","pork","rich","root"] },
  { id: 43, word: "霓虹夜晚",   desc: "下班后的犒劳，城市夜归人",         elements: ["grill","spicy","poultry","rich","sauce"] },
  { id: 44, word: "初雪时分",   desc: "第一场雪，该吃顿暖和的",           elements: ["winter","slowCook","beefLamb","rich","braise"] },
  { id: 45, word: "梅雨季节",   desc: "潮湿闷热，需要开胃的刺激",         elements: ["spicy","sourSweet","cold","poultry","stirFry"] },
  { id: 46, word: "稻花香里",   desc: "稻田飘香，农家菜的质朴",           elements: ["pork","root","steam","sauce","autumn"] },
  { id: 47, word: "荷塘月色",   desc: "夏夜荷塘边，清风送来的雅致",       elements: ["light","root","steam","summer","cold"] },
  { id: 48, word: "巴山夜雨",   desc: "山城的雨夜，麻辣是最好的陪伴",     elements: ["spicy","boil","dryPot","beefLamb","poultry"] },
  { id: 49, word: "岭南风味",   desc: "南国的食材，清淡中见真功夫",       elements: ["light","steam","blanch","tropical","seafood"] },
  { id: 50, word: "塞外风情",   desc: "草原的辽阔，都在炙烤的肉香里",     elements: ["beefLamb","grill","smoked","rich","winter"] },
  { id: 51, word: "江南水乡",   desc: "乌篷船摇过，河鲜肥美时",           elements: ["riverFood","light","steam","sourSweet","summer"] },
  { id: 52, word: "云贵高原",   desc: "酸辣交织，高原上的热烈滋味",       elements: ["spicy","sourSweet","fermented","poultry","dryPot"] },
  { id: 53, word: "东北人家",   desc: "实在的分量，朴实的味道",           elements: ["pork","braise","sauce","root","winter"] },
  { id: 54, word: "西北味道",   desc: "大碗的面，大块的肉，痛快的吃",     elements: ["beefLamb","grill","spicy","rich","sauce"] },
  { id: 55, word: "川渝江湖",   desc: "火锅之外的川味江湖菜",             elements: ["spicy","boil","dryPot","stirFry","pork"] },
  { id: 56, word: "本帮风味",   desc: "浓油赤酱，上海人家的精致",         elements: ["braise","sauce","rich","seafood","sourSweet"] },
  { id: 57, word: "客家味道",   desc: "迁徙中的味觉记忆，咸香浓郁",       elements: ["pork","poultry","sauce","steam","fermented"] },
  { id: 58, word: "潮汕鲜味",   desc: "极致的新鲜，海的馈赠",             elements: ["seafood","blanch","light","umami","steam"] },
  { id: 59, word: "新疆风味",   desc: "孜然的香，羊肉的嫩，西域风情",     elements: ["beefLamb","grill","spicy","rich","smoked"] },
  { id: 60, word: "家的味道",   desc: "就是妈妈做的那种味道",             elements: ["egg","pork","stirFry","light","garlic"] },
  // 夏季 · 解暑
  { id: 61, word: "冰工厂",     desc: "冰箱门一开，冷气扑面而来",         elements: ["coolDown","cold","summer","melon","sourSweet"] },
  { id: 62, word: "夏日凉方",   desc: "老祖宗的消暑智慧都在碗里",         elements: ["coolDown","light","summer","blanch","leafy"] },
  { id: 63, word: "消暑计划",   desc: "30°C以上，启动降温食谱",           elements: ["coolDown","cold","sourSweet","summer","root"] },
  { id: 64, word: "泳池派对",   desc: "水花四溅，来点爽的",               elements: ["coolDown","grill","summer","seafood","spicy"] },
  // 冬季 · 暖身
  { id: 65, word: "暖炉夜话",   desc: "围着炉火，咕嘟咕嘟的小锅",         elements: ["warmUp","winter","slowCook","rich","beefLamb"] },
  { id: 66, word: "初雪火锅",   desc: "下雪天，火锅天",                   elements: ["warmUp","spicy","winter","dryPot","boil"] },
  { id: 67, word: "冬日暖阳",   desc: "阳光照在汤碗上，冒着热气",         elements: ["warmUp","beefLamb","winter","braise","root"] },
  // 秋季 · 润燥
  { id: 68, word: "秋风起",     desc: "起风了，该贴秋膘了",                elements: ["moisten","autumn","mushroom","slowCook","rich"] },
  { id: 69, word: "桂香时节",   desc: "桂花飘香，甜润入心",                elements: ["moisten","sourSweet","autumn","steam","root"] },
  { id: 70, word: "秋收满仓",   desc: "丰收的季节，什么都想来一点",       elements: ["moisten","autumn","pork","braise","mushroom"] },
  // 春季 · 生发
  { id: 71, word: "咬春",       desc: "咬一口春天，满嘴鲜嫩",             elements: ["revive","spring","leafy","light","egg"] },
  { id: 72, word: "万物生",     desc: "春雨过后，山林里的馈赠",           elements: ["revive","bamboo","spring","umami","steam"] },
];

// ---- 菜谱 (200+道) ----
const RECIPES = [
  // ========== 荤菜 (85道) ==========
  { id: 1,  name: "麻婆豆腐",       cat: "荤", elements: ["spicy","tofu","sauce","pork","stirFry"], tags: ["四川","麻辣","下饭"], ingredients:[{n:"嫩豆腐",a:1,u:"块"},{n:"猪肉末",a:100,u:"g"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"花椒粉",a:1,u:"小勺",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"小葱",a:2,u:"根"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 2,  name: "水煮肉片",       cat: "荤", elements: ["spicy","boil","pork","rich"], tags: ["四川","麻辣","硬菜"], ingredients:[{n:"猪里脊",a:300,u:"g"},{n:"大白菜",a:200,u:"g"},{n:"豆芽",a:150,u:"g"},{n:"干辣椒",a:10,u:"个"},{n:"花椒",a:1,u:"把",s:!0},{n:"郫县豆瓣酱",a:1.5,u:"勺",s:!0},{n:"蒜",a:5,u:"瓣"},{n:"姜",a:1,u:"块"},{n:"鸡蛋清",a:1,u:"个"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 3,  name: "宫保鸡丁",       cat: "荤", elements: ["poultry","spicy","sourSweet","stirFry"], tags: ["四川","酸甜辣","经典"], ingredients:[{n:"鸡胸肉",a:250,u:"g"},{n:"花生米",a:50,u:"g"},{n:"黄瓜",a:1,u:"根"},{n:"胡萝卜",a:1,u:"根"},{n:"干辣椒",a:6,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"醋",a:1,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"白糖",a:1,u:"勺"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 4,  name: "回锅肉",         cat: "荤", elements: ["pork","spicy","sauce","stirFry"], tags: ["四川","经典","下饭"], ingredients:[{n:"五花肉",a:300,u:"g"},{n:"青蒜苗",a:3,u:"根"},{n:"青椒",a:2,u:"个"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"豆豉",a:1,u:"小勺",s:!0},{n:"姜",a:1,u:"小块"},{n:"蒜",a:3,u:"瓣"},{n:"甜面酱",a:1,u:"小勺",s:!0}] },
  { id: 5,  name: "鱼香肉丝",       cat: "荤", elements: ["pork","sourSweet","spicy","stirFry"], tags: ["四川","酸甜辣","鱼香味"], ingredients:[{n:"猪里脊",a:250,u:"g"},{n:"木耳",a:50,u:"g"},{n:"胡萝卜",a:1,u:"根"},{n:"青椒",a:2,u:"个"},{n:"泡椒",a:3,u:"个",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"葱",a:2,u:"根"},{n:"醋",a:1.5,u:"勺"},{n:"白糖",a:1,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 6,  name: "辣子鸡",         cat: "荤", elements: ["poultry","spicy","stirFry","dryPot"], tags: ["四川","干香","麻辣"], ingredients:[{n:"鸡腿肉",a:400,u:"g"},{n:"干辣椒",a:20,u:"个"},{n:"花椒",a:1,u:"把",s:!0},{n:"蒜",a:5,u:"瓣"},{n:"姜",a:1,u:"块"},{n:"葱",a:3,u:"根"},{n:"料酒",a:1,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"白糖",a:1,u:"小勺"}] },
  { id: 7,  name: "夫妻肺片",       cat: "荤", elements: ["beefLamb","spicy","cold","sauce"], tags: ["四川","凉菜","麻辣"], ingredients:[{n:"牛腱子",a:200,u:"g"},{n:"牛百叶",a:150,u:"g"},{n:"牛舌",a:100,u:"g"},{n:"香菜",a:2,u:"根"},{n:"花生碎",a:30,u:"g"},{n:"红油",a:2,u:"勺",s:!0},{n:"花椒油",a:1,u:"勺",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"醋",a:1,u:"勺"},{n:"生抽",a:1,u:"勺"}] },
  { id: 8,  name: "剁椒鱼头",       cat: "荤", elements: ["riverFood","spicy","steam","fermented"], tags: ["湖南","鲜辣","蒸菜"], ingredients:[{n:"胖头鱼头",a:1,u:"个"},{n:"剁椒",a:150,u:"g",s:!0},{n:"泡椒",a:50,u:"g",s:!0},{n:"蒜",a:5,u:"瓣"},{n:"姜",a:1,u:"大块"},{n:"葱",a:3,u:"根"},{n:"蒸鱼豉油",a:2,u:"勺",s:!0},{n:"料酒",a:2,u:"勺"}] },
  { id: 9,  name: "小炒肉",         cat: "荤", elements: ["pork","spicy","stirFry","garlic"], tags: ["湖南","香辣","快手"], ingredients:[{n:"五花肉",a:250,u:"g"},{n:"青椒",a:4,u:"个"},{n:"蒜",a:5,u:"瓣"},{n:"豆豉",a:1,u:"勺",s:!0},{n:"生抽",a:1,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:1,u:"勺"}] },
  { id: 10, name: "辣椒炒肉",       cat: "荤", elements: ["pork","spicy","stirFry"], tags: ["湖南","家常","下饭"], ingredients:[{n:"猪瘦肉",a:250,u:"g"},{n:"青椒",a:4,u:"个"},{n:"红椒",a:2,u:"个"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"豆豉",a:1,u:"小勺",s:!0}] },
  { id: 11, name: "酸豆角肉末",     cat: "荤", elements: ["pork","fermented","spicy","stirFry"], tags: ["湖南","酸辣","下饭"], ingredients:[{n:"猪肉末",a:200,u:"g"},{n:"酸豆角",a:150,u:"g",s:!0},{n:"干辣椒",a:5,u:"个"},{n:"蒜",a:3,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"生抽",a:1,u:"勺"}] },
  { id: 12, name: "粉蒸肉",         cat: "荤", elements: ["pork","steam","rich","autumn"], tags: ["湖北","软糯","宴客"], ingredients:[{n:"五花肉",a:350,u:"g"},{n:"蒸肉米粉",a:100,u:"g",s:!0},{n:"红薯",a:1,u:"个"},{n:"姜",a:1,u:"小块"},{n:"葱",a:2,u:"根"},{n:"生抽",a:1,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:1,u:"勺"},{n:"腐乳汁",a:1,u:"勺",s:!0}] },
  { id: 13, name: "武昌鱼",         cat: "荤", elements: ["riverFood","steam","light","umami"], tags: ["湖北","清蒸","本味"], ingredients:[{n:"武昌鱼",a:1,u:"条"},{n:"葱",a:3,u:"根"},{n:"姜",a:1,u:"大块"},{n:"蒸鱼豉油",a:2,u:"勺",s:!0},{n:"料酒",a:1,u:"勺"},{n:"红椒",a:1,u:"个"}] },
  { id: 14, name: "腊肉炒菜薹",     cat: "荤", elements: ["smoked","pork","leafy","stirFry"], tags: ["湖北","时令","腊味"], ingredients:[{n:"腊肉",a:150,u:"g",s:!0},{n:"红菜薹",a:300,u:"g"},{n:"蒜",a:3,u:"瓣"},{n:"干辣椒",a:3,u:"个"},{n:"盐",a:1,u:"小勺"}] },
  { id: 15, name: "白切鸡",         cat: "荤", elements: ["poultry","light","blanch","umami"], tags: ["广东","清淡","本味"], ingredients:[{n:"三黄鸡",a:1,u:"只"},{n:"姜",a:1,u:"大块"},{n:"葱",a:3,u:"根"},{n:"沙姜",a:1,u:"块",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"花生油",a:2,u:"勺"}] },
  { id: 16, name: "叉烧",           cat: "荤", elements: ["pork","grill","sourSweet","rich"], tags: ["广东","蜜汁","烧烤"], ingredients:[{n:"猪梅花肉",a:400,u:"g"},{n:"叉烧酱",a:3,u:"勺",s:!0},{n:"蜂蜜",a:1,u:"勺",s:!0},{n:"生抽",a:1,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:1,u:"勺"},{n:"蒜",a:3,u:"瓣"}] },
  { id: 17, name: "菠萝咕咾肉",     cat: "荤", elements: ["pork","sourSweet","tropical","stirFry"], tags: ["广东","酸甜","果味"], ingredients:[{n:"猪里脊",a:300,u:"g"},{n:"菠萝",a:200,u:"g"},{n:"青椒",a:1,u:"个"},{n:"红椒",a:1,u:"个"},{n:"番茄酱",a:2,u:"勺",s:!0},{n:"白糖",a:1.5,u:"勺"},{n:"白醋",a:1,u:"勺"},{n:"鸡蛋",a:1,u:"个"},{n:"面粉",a:50,u:"g"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 18, name: "豉汁蒸排骨",     cat: "荤", elements: ["pork","steam","sauce","fermented"], tags: ["广东","豉香","蒸"], ingredients:[{n:"猪小排",a:350,u:"g"},{n:"豆豉",a:2,u:"勺",s:!0},{n:"蒜",a:4,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"生抽",a:1,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:1,u:"勺"},{n:"水淀粉",a:1,u:"勺",s:!0},{n:"白糖",a:1,u:"小勺"}] },
  { id: 19, name: "红烧肉",         cat: "荤", elements: ["pork","braise","rich","sauce"], tags: ["家常","硬菜","软糯"], ingredients:[{n:"五花肉",a:400,u:"g"},{n:"冰糖",a:30,u:"g"},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"勺"},{n:"料酒",a:2,u:"勺"},{n:"八角",a:2,u:"个"},{n:"桂皮",a:1,u:"小块",s:!0},{n:"香叶",a:2,u:"片",s:!0},{n:"姜",a:1,u:"块"},{n:"葱",a:2,u:"根"}] },
  { id: 20, name: "糖醋排骨",       cat: "荤", elements: ["pork","sourSweet","braise","rich"], tags: ["家常","酸甜","经典"], ingredients:[{n:"猪小排",a:400,u:"g"},{n:"白糖",a:2,u:"勺"},{n:"醋",a:2,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:1,u:"勺"},{n:"姜",a:1,u:"块"},{n:"葱",a:2,u:"根"}] },
  { id: 21, name: "可乐鸡翅",       cat: "荤", elements: ["poultry","sourSweet","braise","sauce"], tags: ["家常","简单","孩子爱"], ingredients:[{n:"鸡翅中",a:10,u:"个"},{n:"可乐",a:1,u:"罐"},{n:"生抽",a:1.5,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:1,u:"勺"},{n:"姜",a:1,u:"块"},{n:"葱",a:2,u:"根"},{n:"八角",a:1,u:"个"}] },
  { id: 22, name: "青椒肉丝",       cat: "荤", elements: ["pork","stirFry","garlic","light"], tags: ["家常","快手","经典"], ingredients:[{n:"猪里脊",a:250,u:"g"},{n:"青椒",a:3,u:"个"},{n:"蒜",a:3,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"生抽",a:1,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 23, name: "蒜蓉虾",         cat: "荤", elements: ["seafood","garlic","steam","umami"], tags: ["海鲜","蒜香","快手"], ingredients:[{n:"大虾",a:300,u:"g"},{n:"蒜",a:8,u:"瓣"},{n:"葱",a:2,u:"根"},{n:"蒸鱼豉油",a:1,u:"勺",s:!0},{n:"料酒",a:1,u:"勺"},{n:"粉丝",a:50,u:"g"}] },
  { id: 24, name: "清蒸鲈鱼",       cat: "荤", elements: ["riverFood","steam","light","umami"], tags: ["广东","清蒸","鲜美"], ingredients:[{n:"鲈鱼",a:1,u:"条"},{n:"葱",a:3,u:"根"},{n:"姜",a:1,u:"大块"},{n:"蒸鱼豉油",a:2,u:"勺",s:!0},{n:"料酒",a:1,u:"勺"},{n:"红椒",a:1,u:"个"}] },
  { id: 25, name: "葱爆羊肉",       cat: "荤", elements: ["beefLamb","stirFry","garlic","winter"], tags: ["清真","爆炒","温补"], ingredients:[{n:"羊肉片",a:300,u:"g"},{n:"大葱",a:3,u:"根"},{n:"蒜",a:3,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"生抽",a:1,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:1,u:"勺"},{n:"孜然粉",a:1,u:"小勺"},{n:"辣椒粉",a:1,u:"小勺"}] },
  { id: 26, name: "土豆烧牛肉",     cat: "荤", elements: ["beefLamb","root","braise","rich"], tags: ["家常","硬菜","暖身"], ingredients:[{n:"牛腩",a:400,u:"g"},{n:"土豆",a:2,u:"个"},{n:"胡萝卜",a:1,u:"根"},{n:"洋葱",a:1,u:"个"},{n:"八角",a:2,u:"个"},{n:"桂皮",a:1,u:"小块",s:!0},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"勺"},{n:"料酒",a:2,u:"勺"},{n:"姜",a:1,u:"块"},{n:"蒜",a:3,u:"瓣"}] },
  { id: 27, name: "干煸四季豆",     cat: "荤", elements: ["pork","spicy","stirFry","dryPot"], tags: ["四川","干香","下饭"], ingredients:[{n:"四季豆",a:300,u:"g"},{n:"猪肉末",a:80,u:"g"},{n:"干辣椒",a:6,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"芽菜",a:1,u:"勺",s:!0}] },
  { id: 28, name: "酸菜鱼",         cat: "荤", elements: ["riverFood","fermented","spicy","rich"], tags: ["四川","酸辣","大菜"], ingredients:[{n:"草鱼",a:1,u:"条"},{n:"酸菜",a:200,u:"g",s:!0},{n:"干辣椒",a:10,u:"个"},{n:"花椒",a:1,u:"把",s:!0},{n:"蒜",a:5,u:"瓣"},{n:"姜",a:1,u:"大块"},{n:"泡椒",a:5,u:"个",s:!0},{n:"鸡蛋清",a:1,u:"个"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 29, name: "红烧排骨",       cat: "荤", elements: ["pork","braise","rich","sauce"], tags: ["家常","硬菜","入味"], ingredients:[{n:"猪排骨",a:400,u:"g"},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"勺"},{n:"料酒",a:2,u:"勺"},{n:"冰糖",a:25,u:"g"},{n:"八角",a:2,u:"个"},{n:"桂皮",a:1,u:"小块",s:!0},{n:"姜",a:1,u:"块"},{n:"葱",a:2,u:"根"}] },
  { id: 30, name: "可乐排骨",       cat: "荤", elements: ["pork","sourSweet","braise"], tags: ["家常","简单","甜香"], ingredients:[{n:"猪排骨",a:400,u:"g"},{n:"可乐",a:1,u:"罐"},{n:"生抽",a:1.5,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:1,u:"勺"},{n:"姜",a:1,u:"块"},{n:"八角",a:1,u:"个"}] },
  { id: 31, name: "京酱肉丝",       cat: "荤", elements: ["pork","sauce","stirFry","rich"], tags: ["北京","酱香","卷饼"], ingredients:[{n:"猪里脊",a:300,u:"g"},{n:"大葱",a:1,u:"根"},{n:"黄瓜",a:1,u:"根"},{n:"甜面酱",a:2,u:"勺",s:!0},{n:"生抽",a:1,u:"勺"},{n:"白糖",a:1,u:"小勺"},{n:"水淀粉",a:1,u:"勺",s:!0},{n:"豆腐皮",a:4,u:"张"}] },
  { id: 32, name: "蚝油牛肉",       cat: "荤", elements: ["beefLamb","umami","stirFry","sauce"], tags: ["广东","蚝油","嫩滑"], ingredients:[{n:"牛肉",a:250,u:"g"},{n:"青椒",a:2,u:"个"},{n:"洋葱",a:1,u:"个"},{n:"蚝油",a:2,u:"勺",s:!0},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"},{n:"水淀粉",a:1,u:"勺",s:!0},{n:"蒜",a:3,u:"瓣"}] },
  { id: 33, name: "孜然牛肉",       cat: "荤", elements: ["beefLamb","grill","spicy","dryPot"], tags: ["西北","孜然","干香"], ingredients:[{n:"牛肉",a:300,u:"g"},{n:"孜然粉",a:2,u:"小勺"},{n:"辣椒粉",a:1,u:"小勺"},{n:"洋葱",a:1,u:"个"},{n:"青椒",a:2,u:"个"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"}] },
  { id: 34, name: "蒜香鸡翅",       cat: "荤", elements: ["poultry","garlic","grill","rich"], tags: ["家常","蒜香","下酒"], ingredients:[{n:"鸡翅中",a:10,u:"个"},{n:"蒜",a:8,u:"瓣"},{n:"生抽",a:1.5,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"料酒",a:1,u:"勺"},{n:"蜂蜜",a:1,u:"小勺",s:!0},{n:"黑胡椒",a:1,u:"小勺"}] },
  { id: 35, name: "啤酒鸭",         cat: "荤", elements: ["poultry","braise","rich","sauce"], tags: ["湖北","啤酒","硬菜"], ingredients:[{n:"鸭肉",a:500,u:"g"},{n:"啤酒",a:1,u:"罐"},{n:"干辣椒",a:6,u:"个"},{n:"八角",a:2,u:"个"},{n:"桂皮",a:1,u:"小块",s:!0},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"勺"},{n:"姜",a:1,u:"大块"},{n:"蒜",a:5,u:"瓣"}] },
  { id: 36, name: "三杯鸡",         cat: "荤", elements: ["poultry","sauce","braise","rich"], tags: ["台湾","三杯","酱香"], ingredients:[{n:"鸡腿肉",a:400,u:"g"},{n:"米酒",a:1,u:"碗"},{n:"生抽",a:1,u:"碗"},{n:"麻油",a:1,u:"碗"},{n:"蒜",a:8,u:"瓣"},{n:"姜",a:1,u:"大块"},{n:"九层塔",a:1,u:"把",s:!0},{n:"冰糖",a:15,u:"g"}] },
  { id: 37, name: "红烧带鱼",       cat: "荤", elements: ["seafood","braise","rich","sauce"], tags: ["家常","海鲜","入味"], ingredients:[{n:"带鱼",a:400,u:"g"},{n:"生抽",a:1.5,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:2,u:"勺"},{n:"醋",a:1,u:"勺"},{n:"白糖",a:1,u:"小勺"},{n:"姜",a:1,u:"块"},{n:"蒜",a:3,u:"瓣"},{n:"葱",a:2,u:"根"}] },
  { id: 38, name: "椒盐虾",         cat: "荤", elements: ["seafood","grill","spicy","garlic"], tags: ["粤式","椒盐","下酒"], ingredients:[{n:"大虾",a:300,u:"g"},{n:"椒盐",a:1,u:"勺",s:!0},{n:"蒜",a:5,u:"瓣"},{n:"干辣椒",a:4,u:"个"},{n:"葱",a:2,u:"根"},{n:"料酒",a:1,u:"勺"},{n:"淀粉",a:2,u:"勺"}] },
  { id: 39, name: "咖喱鸡肉",       cat: "荤", elements: ["poultry","rich","slowCook","tropical"], tags: ["泰式","咖喱","浓郁"], ingredients:[{n:"鸡腿肉",a:350,u:"g"},{n:"土豆",a:2,u:"个"},{n:"胡萝卜",a:1,u:"根"},{n:"洋葱",a:1,u:"个"},{n:"咖喱块",a:2,u:"块",s:!0},{n:"椰浆",a:100,u:"ml",s:!0}] },
  { id: 40, name: "番茄炖牛腩",     cat: "荤", elements: ["beefLamb","sourSweet","slowCook","rich"], tags: ["家常","酸甜","暖身"], ingredients:[{n:"牛腩",a:400,u:"g"},{n:"番茄",a:3,u:"个"},{n:"土豆",a:2,u:"个"},{n:"洋葱",a:1,u:"个"},{n:"番茄酱",a:1,u:"勺",s:!0},{n:"生抽",a:1.5,u:"勺"},{n:"八角",a:2,u:"个"},{n:"姜",a:1,u:"块"}] },
  { id: 41, name: "红烧鸡块",       cat: "荤", elements: ["poultry","braise","rich","sauce"], tags: ["家常","红烧","下饭"], ingredients:[{n:"鸡腿",a:400,u:"g"},{n:"土豆",a:2,u:"个"},{n:"青椒",a:2,u:"个"},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"},{n:"八角",a:2,u:"个"},{n:"姜",a:1,u:"块"},{n:"蒜",a:3,u:"瓣"}] },
  { id: 42, name: "香辣虾",         cat: "荤", elements: ["seafood","spicy","stirFry","dryPot"], tags: ["川味","香辣","虾"], ingredients:[{n:"大虾",a:300,u:"g"},{n:"干辣椒",a:8,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"蒜",a:5,u:"瓣"},{n:"姜",a:1,u:"块"},{n:"葱",a:2,u:"根"}] },
  { id: 43, name: "泡椒牛肉",       cat: "荤", elements: ["beefLamb","spicy","fermented","stirFry"], tags: ["川味","泡椒","嫩滑"], ingredients:[{n:"牛肉",a:250,u:"g"},{n:"泡椒",a:8,u:"个",s:!0},{n:"泡姜",a:1,u:"块",s:!0},{n:"芹菜",a:2,u:"根"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 44, name: "盐煎肉",         cat: "荤", elements: ["pork","sauce","stirFry","garlic"], tags: ["四川","干香","下饭"], ingredients:[{n:"猪瘦肉",a:300,u:"g"},{n:"蒜苗",a:3,u:"根"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"豆豉",a:1,u:"小勺",s:!0},{n:"姜",a:1,u:"小块"},{n:"白糖",a:1,u:"小勺"}] },
  { id: 45, name: "葱油鸡",         cat: "荤", elements: ["poultry","light","blanch","garlic"], tags: ["粤式","葱油","嫩滑"], ingredients:[{n:"鸡",a:1,u:"只"},{n:"葱",a:6,u:"根"},{n:"姜",a:1,u:"大块"},{n:"料酒",a:2,u:"勺"},{n:"生抽",a:2,u:"勺"},{n:"花生油",a:3,u:"勺"}] },
  { id: 46, name: "黑椒牛柳",       cat: "荤", elements: ["beefLamb","stirFry","rich","grill"], tags: ["西式","黑椒","嫩滑"], ingredients:[{n:"牛里脊",a:250,u:"g"},{n:"青椒",a:1,u:"个"},{n:"红椒",a:1,u:"个"},{n:"洋葱",a:1,u:"个"},{n:"黑胡椒",a:1.5,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 47, name: "椒麻鸡",         cat: "荤", elements: ["poultry","spicy","cold","umami"], tags: ["四川","椒麻","凉菜"], ingredients:[{n:"鸡腿",a:3,u:"个"},{n:"花椒",a:2,u:"把",s:!0},{n:"青花椒",a:1,u:"把",s:!0},{n:"青椒",a:3,u:"个"},{n:"葱",a:3,u:"根"},{n:"姜",a:1,u:"块"},{n:"生抽",a:1.5,u:"勺"},{n:"花椒油",a:1,u:"勺",s:!0}] },
  { id: 48, name: "葱烧海参",       cat: "荤", elements: ["seafood","braise","rich","sauce"], tags: ["鲁菜","海味","宴客"], ingredients:[{n:"海参",a:4,u:"只"},{n:"大葱",a:3,u:"根"},{n:"生抽",a:2,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"糖",a:1,u:"小勺"},{n:"水淀粉",a:1,u:"勺",s:!0},{n:"姜",a:1,u:"块"}] },
  { id: 49, name: "干锅牛蛙",       cat: "荤", elements: ["poultry","spicy","dryPot","garlic"], tags: ["川味","干锅","过瘾"], ingredients:[{n:"牛蛙",a:3,u:"只"},{n:"干辣椒",a:10,u:"个"},{n:"花椒",a:1,u:"把",s:!0},{n:"蒜",a:6,u:"瓣"},{n:"姜",a:1,u:"大块"},{n:"洋葱",a:1,u:"个"},{n:"青椒",a:2,u:"个"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"芹菜",a:2,u:"根"}] },
  { id: 50, name: "黄焖鸡",         cat: "荤", elements: ["poultry","braise","rich","slowCook"], tags: ["山东","黄焖","下饭"], ingredients:[{n:"鸡腿肉",a:400,u:"g"},{n:"土豆",a:2,u:"个"},{n:"香菇",a:6,u:"个"},{n:"青椒",a:2,u:"个"},{n:"生抽",a:2,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"老抽",a:1,u:"小勺"},{n:"姜",a:1,u:"块"},{n:"蒜",a:3,u:"瓣"}] },
  { id: 51, name: "辣炒花蛤",       cat: "荤", elements: ["seafood","spicy","stirFry","garlic"], tags: ["海鲜","麻辣","快手"], ingredients:[{n:"花蛤",a:500,u:"g"},{n:"干辣椒",a:6,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"蒜",a:5,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"葱",a:2,u:"根"},{n:"料酒",a:1,u:"勺"}] },
  { id: 52, name: "梅菜扣肉",       cat: "荤", elements: ["pork","steam","rich","fermented"], tags: ["客家","蒸菜","硬菜"], ingredients:[{n:"五花肉",a:400,u:"g"},{n:"梅干菜",a:100,u:"g",s:!0},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"},{n:"白糖",a:1,u:"勺"},{n:"姜",a:1,u:"块"}] },
  { id: 53, name: "芹菜牛肉",       cat: "荤", elements: ["beefLamb","stirFry","light","garlic"], tags: ["家常","快炒","脆嫩"], ingredients:[{n:"牛肉",a:200,u:"g"},{n:"芹菜",a:3,u:"根"},{n:"红椒",a:1,u:"个"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 54, name: "蒜蓉粉丝蒸虾",   cat: "荤", elements: ["seafood","garlic","steam","umami"], tags: ["粤式","蒜蓉","蒸"], ingredients:[{n:"大虾",a:300,u:"g"},{n:"龙口粉丝",a:1,u:"把"},{n:"蒜",a:8,u:"瓣"},{n:"蒸鱼豉油",a:2,u:"勺",s:!0},{n:"葱",a:2,u:"根"},{n:"料酒",a:1,u:"勺"}] },
  { id: 55, name: "油焖大虾",       cat: "荤", elements: ["seafood","braise","rich","sourSweet"], tags: ["湖北","油焖","酸甜"], ingredients:[{n:"大虾",a:400,u:"g"},{n:"番茄酱",a:2,u:"勺",s:!0},{n:"白糖",a:1,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"},{n:"姜",a:1,u:"块"},{n:"蒜",a:4,u:"瓣"},{n:"葱",a:2,u:"根"}] },
  { id: 56, name: "糖醋里脊",       cat: "荤", elements: ["pork","sourSweet","stirFry","rich"], tags: ["家常","酸甜","酥脆"], ingredients:[{n:"猪里脊",a:300,u:"g"},{n:"番茄酱",a:3,u:"勺",s:!0},{n:"白糖",a:2,u:"勺"},{n:"白醋",a:1.5,u:"勺"},{n:"鸡蛋",a:1,u:"个"},{n:"面粉",a:60,u:"g"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 57, name: "红烧鲫鱼",       cat: "荤", elements: ["riverFood","braise","rich","sauce"], tags: ["家常","红烧","鲜美"], ingredients:[{n:"鲫鱼",a:1,u:"条"},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:2,u:"勺"},{n:"醋",a:1,u:"勺"},{n:"白糖",a:1,u:"小勺"},{n:"姜",a:1,u:"大块"},{n:"蒜",a:3,u:"瓣"},{n:"葱",a:3,u:"根"},{n:"豆瓣酱",a:1,u:"勺"}] },
  { id: 58, name: "烤羊排",         cat: "荤", elements: ["beefLamb","grill","rich","spicy"], tags: ["西北","烧烤","硬菜"], ingredients:[{n:"羊排",a:500,u:"g"},{n:"孜然粉",a:2,u:"勺"},{n:"辣椒粉",a:1,u:"勺"},{n:"蒜",a:5,u:"瓣"},{n:"洋葱",a:1,u:"个"},{n:"料酒",a:2,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"盐",a:1,u:"勺"}] },
  { id: 59, name: "干锅花菜",       cat: "荤", elements: ["pork","spicy","dryPot","garlic"], tags: ["川味","干锅","下饭"], ingredients:[{n:"花菜",a:300,u:"g"},{n:"五花肉",a:100,u:"g"},{n:"干辣椒",a:6,u:"个"},{n:"蒜",a:4,u:"瓣"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"生抽",a:1,u:"勺"},{n:"青椒",a:1,u:"个"}] },
  { id: 60, name: "香煎带鱼",       cat: "荤", elements: ["seafood","grill","light","garlic"], tags: ["家常","香煎","酥脆"], ingredients:[{n:"带鱼",a:350,u:"g"},{n:"姜",a:1,u:"块"},{n:"蒜",a:3,u:"瓣"},{n:"料酒",a:1,u:"勺"},{n:"盐",a:1,u:"小勺"},{n:"淀粉",a:2,u:"勺"}] },
  { id: 61, name: "板栗烧鸡",       cat: "荤", elements: ["poultry","braise","rich","autumn"], tags: ["家常","板栗","滋补"], ingredients:[{n:"鸡腿",a:350,u:"g"},{n:"板栗",a:200,u:"g"},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:1,u:"勺"},{n:"冰糖",a:15,u:"g"},{n:"姜",a:1,u:"块"},{n:"八角",a:1,u:"个"}] },
  { id: 62, name: "辣炒鱿鱼",       cat: "荤", elements: ["seafood","spicy","stirFry","garlic"], tags: ["海鲜","香辣","快手"], ingredients:[{n:"鱿鱼",a:300,u:"g"},{n:"青椒",a:2,u:"个"},{n:"洋葱",a:1,u:"个"},{n:"干辣椒",a:5,u:"个"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"料酒",a:1,u:"勺"}] },
  { id: 63, name: "洋葱炒肉",       cat: "荤", elements: ["pork","stirFry","light","garlic"], tags: ["家常","简单","快手"], ingredients:[{n:"猪瘦肉",a:200,u:"g"},{n:"洋葱",a:1,u:"个"},{n:"青椒",a:1,u:"个"},{n:"蒜",a:2,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:1,u:"小勺"}] },
  { id: 64, name: "豆角焖排骨",     cat: "荤", elements: ["pork","braise","rich","sauce"], tags: ["家常","焖菜","入味"], ingredients:[{n:"猪排骨",a:350,u:"g"},{n:"豆角",a:250,u:"g"},{n:"生抽",a:1.5,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:1,u:"勺"},{n:"八角",a:1,u:"个"},{n:"姜",a:1,u:"块"},{n:"蒜",a:3,u:"瓣"}] },
  { id: 65, name: "粉蒸排骨",       cat: "荤", elements: ["pork","steam","rich","autumn"], tags: ["湖北","粉蒸","软糯"], ingredients:[{n:"猪排骨",a:350,u:"g"},{n:"蒸肉米粉",a:80,u:"g",s:!0},{n:"土豆",a:1,u:"个"},{n:"生抽",a:1,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"料酒",a:1,u:"勺"},{n:"姜",a:1,u:"块"},{n:"葱",a:2,u:"根"}] },
  { id: 66, name: "酸汤肥牛",       cat: "荤", elements: ["beefLamb","sourSweet","spicy","slowCook"], tags: ["贵州","酸汤","开胃"], ingredients:[{n:"肥牛卷",a:300,u:"g"},{n:"金针菇",a:150,u:"g"},{n:"番茄",a:2,u:"个"},{n:"泡椒",a:5,u:"个",s:!0},{n:"黄灯笼椒酱",a:1,u:"勺",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"姜",a:1,u:"块"},{n:"白醋",a:1,u:"勺"}] },
  { id: 67, name: "葱油鱼片",       cat: "荤", elements: ["riverFood","light","steam","blanch"], tags: ["粤式","葱油","嫩滑"], ingredients:[{n:"鱼片",a:300,u:"g"},{n:"葱",a:5,u:"根"},{n:"姜",a:1,u:"块"},{n:"蒸鱼豉油",a:2,u:"勺",s:!0},{n:"料酒",a:1,u:"勺"},{n:"淀粉",a:1,u:"勺"}] },
  { id: 68, name: "咖喱牛肉",       cat: "荤", elements: ["beefLamb","rich","slowCook","tropical"], tags: ["泰式","咖喱","浓郁"], ingredients:[{n:"牛腩",a:350,u:"g"},{n:"土豆",a:2,u:"个"},{n:"胡萝卜",a:1,u:"根"},{n:"洋葱",a:1,u:"个"},{n:"咖喱块",a:2,u:"块",s:!0},{n:"椰浆",a:100,u:"ml",s:!0}] },
  { id: 69, name: "孜然羊肉",       cat: "荤", elements: ["beefLamb","grill","spicy","dryPot"], tags: ["新疆","孜然","烧烤"], ingredients:[{n:"羊肉",a:300,u:"g"},{n:"孜然粉",a:2,u:"勺"},{n:"辣椒粉",a:1,u:"小勺"},{n:"洋葱",a:1,u:"个"},{n:"香菜",a:2,u:"根"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"}] },
  { id: 70, name: "泡菜炒五花",     cat: "荤", elements: ["pork","fermented","spicy","stirFry"], tags: ["韩式","泡菜","开胃"], ingredients:[{n:"五花肉",a:250,u:"g"},{n:"韩式泡菜",a:200,u:"g",s:!0},{n:"洋葱",a:1,u:"个"},{n:"蒜",a:3,u:"瓣"},{n:"韩式辣酱",a:1,u:"勺",s:!0},{n:"生抽",a:1,u:"小勺"}] },
  { id: 71, name: "炒肥肠",         cat: "荤", elements: ["pork","spicy","stirFry","dryPot"], tags: ["川味","内脏","下酒"], ingredients:[{n:"卤肥肠",a:250,u:"g"},{n:"青椒",a:3,u:"个"},{n:"干辣椒",a:8,u:"个"},{n:"花椒",a:1,u:"把",s:!0},{n:"蒜",a:4,u:"瓣"},{n:"姜",a:1,u:"块"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"生抽",a:1,u:"勺"}] },
  { id: 72, name: "蒜香排骨",       cat: "荤", elements: ["pork","garlic","grill","rich"], tags: ["粤式","蒜香","酥脆"], ingredients:[{n:"猪排骨",a:400,u:"g"},{n:"蒜",a:10,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"料酒",a:1,u:"勺"},{n:"淀粉",a:2,u:"勺"},{n:"面包糠",a:50,u:"g"}] },
  { id: 73, name: "萝卜烧牛肉",     cat: "荤", elements: ["beefLamb","root","braise","winter"], tags: ["家常","萝卜","暖身"], ingredients:[{n:"牛腩",a:350,u:"g"},{n:"白萝卜",a:1,u:"根"},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"勺"},{n:"料酒",a:2,u:"勺"},{n:"八角",a:2,u:"个"},{n:"桂皮",a:1,u:"块",s:!0},{n:"姜",a:1,u:"块"},{n:"蒜",a:3,u:"瓣"}] },
  { id: 75, name: "红烧牛腩",       cat: "荤", elements: ["beefLamb","braise","rich","sauce"], tags: ["家常","硬菜","入味"], ingredients:[{n:"牛腩",a:400,u:"g"},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"勺"},{n:"料酒",a:2,u:"勺"},{n:"冰糖",a:20,u:"g"},{n:"八角",a:2,u:"个"},{n:"桂皮",a:1,u:"块",s:!0},{n:"香叶",a:2,u:"片",s:!0},{n:"姜",a:1,u:"大块"}] },
  { id: 76, name: "青椒炒蛋",       cat: "荤", elements: ["egg","stirFry","light","garlic"], tags: ["家常","快手","简单"], ingredients:[{n:"鸡蛋",a:3,u:"个"},{n:"青椒",a:3,u:"个"},{n:"蒜",a:2,u:"瓣"},{n:"生抽",a:1,u:"小勺"},{n:"盐",a:1,u:"小勺"}] },
  { id: 77, name: "韭菜炒蛋",       cat: "荤", elements: ["egg","stirFry","spring","light"], tags: ["家常","春季","简单"], ingredients:[{n:"鸡蛋",a:3,u:"个"},{n:"韭菜",a:200,u:"g"},{n:"盐",a:1,u:"小勺"}] },
  { id: 78, name: "虾仁滑蛋",       cat: "荤", elements: ["seafood","egg","umami","light"], tags: ["粤式","嫩滑","鲜美"], ingredients:[{n:"虾仁",a:200,u:"g"},{n:"鸡蛋",a:3,u:"个"},{n:"葱",a:2,u:"根"},{n:"料酒",a:1,u:"小勺"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 79, name: "肉末蒸蛋",       cat: "荤", elements: ["egg","pork","steam","light"], tags: ["家常","蒸菜","嫩滑"], ingredients:[{n:"鸡蛋",a:3,u:"个"},{n:"猪肉末",a:80,u:"g"},{n:"生抽",a:1,u:"勺"},{n:"葱",a:1,u:"根"},{n:"姜",a:1,u:"片"}] },
  { id: 80, name: "虎皮青椒",       cat: "荤", elements: ["leafy","grill","sourSweet","garlic"], tags: ["四川","素菜荤做","下饭"], ingredients:[{n:"青椒",a:5,u:"个"},{n:"蒜",a:4,u:"瓣"},{n:"生抽",a:1.5,u:"勺"},{n:"醋",a:1,u:"勺"},{n:"白糖",a:1,u:"小勺"},{n:"豆豉",a:1,u:"小勺",s:!0}] },
  { id: 81, name: "干煸牛肉丝",     cat: "荤", elements: ["beefLamb","spicy","stirFry","dryPot"], tags: ["四川","干香","麻辣"], ingredients:[{n:"牛肉",a:250,u:"g"},{n:"干辣椒",a:10,u:"个"},{n:"花椒",a:1,u:"把",s:!0},{n:"芹菜",a:2,u:"根"},{n:"姜",a:1,u:"小块"},{n:"蒜",a:3,u:"瓣"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"生抽",a:1,u:"勺"}] },
  { id: 82, name: "酱骨架",         cat: "荤", elements: ["pork","braise","sauce","rich"], tags: ["东北","酱香","硬菜"], ingredients:[{n:"猪脊骨",a:500,u:"g"},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"勺"},{n:"黄豆酱",a:2,u:"勺",s:!0},{n:"八角",a:3,u:"个"},{n:"桂皮",a:1,u:"块",s:!0},{n:"香叶",a:3,u:"片",s:!0},{n:"姜",a:1,u:"大块"},{n:"蒜",a:5,u:"瓣"},{n:"冰糖",a:20,u:"g"}] },
  { id: 84, name: "铁板牛肉",       cat: "荤", elements: ["beefLamb","grill","rich","garlic"], tags: ["粤式","铁板","嫩滑"], ingredients:[{n:"牛里脊",a:250,u:"g"},{n:"青椒",a:2,u:"个"},{n:"洋葱",a:1,u:"个"},{n:"黑胡椒",a:1,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"生抽",a:1,u:"勺"},{n:"水淀粉",a:1,u:"勺",s:!0},{n:"蒜",a:3,u:"瓣"}] },
  { id: 85, name: "茶树菇炒腊肉",   cat: "荤", elements: ["smoked","mushroom","stirFry","spicy"], tags: ["湖北","腊味","山珍"], ingredients:[{n:"腊肉",a:150,u:"g",s:!0},{n:"茶树菇",a:200,u:"g"},{n:"青椒",a:2,u:"个"},{n:"蒜",a:3,u:"瓣"},{n:"干辣椒",a:4,u:"个"},{n:"生抽",a:1,u:"小勺"}] },

  { id: 86, name: "蒜蓉蒸龙虾",     cat: "荤", elements: ["seafood","garlic","steam","umami"], tags: ["海鲜","硬菜","宴客"], ingredients:[{n:"龙虾",a:1,u:"只"},{n:"蒜",a:10,u:"瓣"},{n:"葱",a:3,u:"根"},{n:"蒸鱼豉油",a:2,u:"勺",s:!0},{n:"料酒",a:1,u:"勺"},{n:"粉丝",a:1,u:"把"}] },
  { id: 87, name: "葱姜炒蟹",       cat: "荤", elements: ["seafood","stirFry","garlic","umami"], tags: ["海鲜","粤式","鲜美"], ingredients:[{n:"螃蟹",a:2,u:"只"},{n:"葱",a:4,u:"根"},{n:"姜",a:1,u:"大块"},{n:"蒜",a:4,u:"瓣"},{n:"料酒",a:2,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"淀粉",a:1,u:"勺"}] },
  { id: 88, name: "白灼基围虾",     cat: "荤", elements: ["seafood","blanch","light","umami"], tags: ["粤式","白灼","本味"], ingredients:[{n:"基围虾",a:400,u:"g"},{n:"姜",a:1,u:"块"},{n:"葱",a:2,u:"根"},{n:"料酒",a:1,u:"勺"},{n:"生抽",a:2,u:"勺"},{n:"蒜",a:3,u:"瓣"}] },
  { id: 89, name: "蒜蓉粉丝蒸扇贝", cat: "荤", elements: ["seafood","garlic","steam","umami"], tags: ["海鲜","蒜蓉","鲜美"], ingredients:[{n:"扇贝",a:6,u:"只"},{n:"龙口粉丝",a:1,u:"把"},{n:"蒜",a:8,u:"瓣"},{n:"蒸鱼豉油",a:2,u:"勺",s:!0},{n:"葱",a:2,u:"根"},{n:"小米椒",a:2,u:"个"},{n:"料酒",a:1,u:"勺"}] },
  { id: 90, name: "爆炒牛肝菌",     cat: "荤", elements: ["mushroom","spicy","stirFry","garlic"], tags: ["云南","菌菇","下饭"], ingredients:[{n:"牛肝菌",a:300,u:"g"},{n:"干辣椒",a:8,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"蒜",a:5,u:"瓣"},{n:"青椒",a:2,u:"个"},{n:"腊肉",a:80,u:"g"},{n:"生抽",a:1,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0}] },
  { id: 91, name: "毛血旺",         cat: "荤", elements: ["spicy","boil","rich","pork"], tags: ["川渝","麻辣","硬菜"], ingredients:[{n:"鸭血",a:300,u:"g"},{n:"毛肚",a:150,u:"g"},{n:"午餐肉",a:100,u:"g"},{n:"豆芽",a:200,u:"g"},{n:"干辣椒",a:15,u:"个"},{n:"花椒",a:2,u:"把",s:!0},{n:"郫县豆瓣酱",a:2,u:"勺",s:!0},{n:"蒜",a:5,u:"瓣"},{n:"姜",a:1,u:"大块"},{n:"火锅底料",a:1,u:"块",s:!0}] },
  { id: 92, name: "水煮牛肉",       cat: "荤", elements: ["beefLamb","spicy","boil","rich"], tags: ["四川","麻辣","硬菜"], ingredients:[{n:"牛肉",a:300,u:"g"},{n:"豆芽",a:150,u:"g"},{n:"大白菜",a:200,u:"g"},{n:"干辣椒",a:10,u:"个"},{n:"花椒",a:1,u:"把",s:!0},{n:"郫县豆瓣酱",a:1.5,u:"勺",s:!0},{n:"蒜",a:5,u:"瓣"},{n:"姜",a:1,u:"块"},{n:"鸡蛋清",a:1,u:"个"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 93, name: "锅包肉",         cat: "荤", elements: ["pork","sourSweet","stirFry","rich"], tags: ["东北","酸甜","酥脆"], ingredients:[{n:"猪里脊",a:300,u:"g"},{n:"白糖",a:2,u:"勺"},{n:"白醋",a:2,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"},{n:"姜",a:1,u:"小块"},{n:"蒜",a:2,u:"瓣"},{n:"土豆淀粉",a:100,u:"g"},{n:"鸡蛋",a:1,u:"个"}] },
  { id: 94, name: "东坡肉",         cat: "荤", elements: ["pork","braise","rich","sauce","slowCook"], tags: ["浙江","硬菜","入口即化"], ingredients:[{n:"五花肉",a:500,u:"g"},{n:"生抽",a:3,u:"勺"},{n:"老抽",a:2,u:"勺"},{n:"料酒",a:3,u:"勺"},{n:"冰糖",a:40,u:"g"},{n:"葱",a:4,u:"根"},{n:"姜",a:1,u:"大块"},{n:"八角",a:2,u:"个"},{n:"桂皮",a:1,u:"块",s:!0}] },
  { id: 95, name: "干煸鱿鱼须",     cat: "荤", elements: ["seafood","spicy","dryPot","stirFry"], tags: ["川味","干香","下酒"], ingredients:[{n:"鱿鱼须",a:300,u:"g"},{n:"干辣椒",a:10,u:"个"},{n:"花椒",a:1,u:"把",s:!0},{n:"蒜",a:4,u:"瓣"},{n:"姜",a:1,u:"块"},{n:"芹菜",a:2,u:"根"},{n:"孜然粉",a:1,u:"小勺"},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"}] },
  { id: 96, name: "黑椒牛仔骨",     cat: "荤", elements: ["beefLamb","grill","rich","sauce"], tags: ["粤式","黑椒","硬菜"], ingredients:[{n:"牛仔骨",a:400,u:"g"},{n:"洋葱",a:1,u:"个"},{n:"青椒",a:1,u:"个"},{n:"红椒",a:1,u:"个"},{n:"黑胡椒",a:2,u:"勺"},{n:"蚝油",a:1.5,u:"勺",s:!0},{n:"生抽",a:1,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"蒜",a:3,u:"瓣"},{n:"料酒",a:1,u:"勺"}] },
  { id: 97, name: "水煮鱼片",       cat: "荤", elements: ["riverFood","spicy","boil","rich"], tags: ["四川","麻辣","硬菜"], ingredients:[{n:"草鱼片",a:350,u:"g"},{n:"豆芽",a:200,u:"g"},{n:"干辣椒",a:12,u:"个"},{n:"花椒",a:1,u:"把",s:!0},{n:"郫县豆瓣酱",a:1.5,u:"勺",s:!0},{n:"蒜",a:5,u:"瓣"},{n:"姜",a:1,u:"块"},{n:"鸡蛋清",a:1,u:"个"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 98, name: "青花椒鱼",       cat: "荤", elements: ["riverFood","spicy","boil","umami"], tags: ["川渝","青花椒","鲜麻"], ingredients:[{n:"鱼片",a:350,u:"g"},{n:"青花椒",a:2,u:"把",s:!0},{n:"青椒",a:3,u:"个"},{n:"小米椒",a:5,u:"个"},{n:"蒜",a:5,u:"瓣"},{n:"姜",a:1,u:"大块"},{n:"鸡蛋清",a:1,u:"个"},{n:"水淀粉",a:1,u:"勺",s:!0},{n:"料酒",a:1,u:"勺"}] },
  { id: 99, name: "蒜蓉烤生蚝",     cat: "荤", elements: ["seafood","garlic","grill","umami"], tags: ["海鲜","烧烤","蒜蓉"], ingredients:[{n:"生蚝",a:8,u:"只"},{n:"蒜",a:10,u:"瓣"},{n:"小米椒",a:3,u:"个"},{n:"蒸鱼豉油",a:1,u:"勺",s:!0},{n:"葱",a:2,u:"根"},{n:"柠檬",a:1,u:"个"}] },
  { id: 100, name: "香辣蟹",        cat: "荤", elements: ["seafood","spicy","stirFry","dryPot"], tags: ["川味","香辣","宴客"], ingredients:[{n:"螃蟹",a:3,u:"只"},{n:"干辣椒",a:10,u:"个"},{n:"花椒",a:1,u:"把",s:!0},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"蒜",a:6,u:"瓣"},{n:"姜",a:1,u:"大块"},{n:"葱",a:3,u:"根"},{n:"料酒",a:2,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"白糖",a:1,u:"小勺"}] },
  { id: 300, name: "葱油蛏子",      cat: "荤", elements: ["seafood","light","blanch","garlic"], tags: ["海鲜","葱油","鲜美"], ingredients:[{n:"蛏子",a:400,u:"g"},{n:"葱",a:5,u:"根"},{n:"姜",a:1,u:"块"},{n:"蒜",a:3,u:"瓣"},{n:"蒸鱼豉油",a:2,u:"勺",s:!0},{n:"料酒",a:1,u:"勺"}] },
  { id: 301, name: "辣酒煮花螺",    cat: "荤", elements: ["seafood","spicy","slowCook","rich"], tags: ["海鲜","下酒","香辣"], ingredients:[{n:"花螺",a:500,u:"g"},{n:"干辣椒",a:8,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"啤酒",a:1,u:"罐"},{n:"蒜",a:5,u:"瓣"},{n:"姜",a:1,u:"大块"},{n:"葱",a:2,u:"根"}] },
  { id: 302, name: "烤猪蹄",        cat: "荤", elements: ["pork","grill","spicy","rich"], tags: ["烧烤","下酒","胶原"], ingredients:[{n:"猪蹄",a:2,u:"只"},{n:"孜然粉",a:1,u:"勺"},{n:"辣椒粉",a:1,u:"勺"},{n:"蒜",a:5,u:"瓣"},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"勺"},{n:"料酒",a:2,u:"勺"},{n:"八角",a:2,u:"个"},{n:"桂皮",a:1,u:"块",s:!0},{n:"姜",a:1,u:"大块"}] },
  { id: 303, name: "酱牛肉",        cat: "荤", elements: ["beefLamb","braise","sauce","cold"], tags: ["东北","酱香","冷盘"], ingredients:[{n:"牛腱子",a:500,u:"g"},{n:"生抽",a:3,u:"勺"},{n:"老抽",a:2,u:"勺"},{n:"黄豆酱",a:2,u:"勺",s:!0},{n:"八角",a:3,u:"个"},{n:"桂皮",a:1,u:"块",s:!0},{n:"香叶",a:3,u:"片",s:!0},{n:"花椒",a:1,u:"把",s:!0},{n:"姜",a:1,u:"大块"},{n:"葱",a:3,u:"根"},{n:"冰糖",a:20,u:"g"}] },
  { id: 304, name: "脆皮烧肉",      cat: "荤", elements: ["pork","grill","rich","smoked"], tags: ["粤式","烧腊","酥脆"], ingredients:[{n:"带皮五花肉",a:400,u:"g"},{n:"五香粉",a:1,u:"勺",s:!0},{n:"白醋",a:1,u:"勺"},{n:"盐",a:2,u:"小勺"},{n:"料酒",a:1,u:"勺"}] },
  { id: 305, name: "豉油鸡",        cat: "荤", elements: ["poultry","sauce","braise","umami"], tags: ["粤式","豉油","嫩滑"], ingredients:[{n:"鸡",a:1,u:"只"},{n:"生抽",a:4,u:"勺"},{n:"老抽",a:2,u:"勺"},{n:"冰糖",a:30,u:"g"},{n:"八角",a:2,u:"个"},{n:"桂皮",a:1,u:"块",s:!0},{n:"姜",a:1,u:"大块"},{n:"葱",a:3,u:"根"},{n:"料酒",a:2,u:"勺"}] },
  { id: 306, name: "盐焗鸡",        cat: "荤", elements: ["poultry","grill","light","umami"], tags: ["客家","盐焗","嫩滑"], ingredients:[{n:"鸡",a:1,u:"只"},{n:"盐焗鸡粉",a:1,u:"包",s:!0},{n:"姜",a:1,u:"大块"},{n:"葱",a:3,u:"根"},{n:"料酒",a:1,u:"勺"},{n:"粗盐",a:500,u:"g",s:!0}] },
  { id: 307, name: "木须肉",        cat: "荤", elements: ["pork","egg","stirFry","light"], tags: ["东北","家常","丰富"], ingredients:[{n:"猪里脊",a:200,u:"g"},{n:"鸡蛋",a:2,u:"个"},{n:"木耳",a:50,u:"g"},{n:"黄花菜",a:30,u:"g"},{n:"黄瓜",a:1,u:"根"},{n:"蒜",a:2,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 308, name: "红烧牛尾",      cat: "荤", elements: ["beefLamb","braise","rich","slowCook"], tags: ["硬菜","红烧","胶质"], ingredients:[{n:"牛尾",a:500,u:"g"},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1.5,u:"勺"},{n:"料酒",a:3,u:"勺"},{n:"冰糖",a:25,u:"g"},{n:"八角",a:2,u:"个"},{n:"桂皮",a:1,u:"块",s:!0},{n:"香叶",a:2,u:"片",s:!0},{n:"姜",a:1,u:"大块"},{n:"蒜",a:5,u:"瓣"},{n:"胡萝卜",a:1,u:"根"}] },
  { id: 309, name: "香煎小黄鱼",    cat: "荤", elements: ["seafood","grill","light","garlic"], tags: ["海鲜","香煎","酥脆"], ingredients:[{n:"小黄鱼",a:4,u:"条"},{n:"姜",a:1,u:"块"},{n:"蒜",a:3,u:"瓣"},{n:"料酒",a:1,u:"勺"},{n:"盐",a:1,u:"小勺"},{n:"淀粉",a:2,u:"勺"},{n:"葱",a:1,u:"根"}] },
  { id: 310, name: "小炒黄牛肉",     cat: "荤", elements: ["beefLamb","spicy","stirFry","zingy"], tags: ["湖南","鲜辣","下饭"], ingredients:[{n:"黄牛肉",a:250,u:"g"},{n:"小米椒",a:5,u:"个"},{n:"泡椒",a:4,u:"个",s:!0},{n:"香菜",a:2,u:"根"},{n:"蒜",a:4,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"}] },
  { id: 311, name: "泡椒鸡杂",       cat: "荤", elements: ["poultry","spicy","stirFry","fermented"], tags: ["川味","泡椒","下饭"], ingredients:[{n:"鸡杂",a:300,u:"g"},{n:"泡椒",a:8,u:"个",s:!0},{n:"泡姜",a:1,u:"块",s:!0},{n:"芹菜",a:2,u:"根"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"},{n:"花椒",a:1,u:"小把",s:!0}] },
  { id: 312, name: "剁椒蒸排骨",     cat: "荤", elements: ["pork","spicy","steam","fermented"], tags: ["湖南","剁椒","少油"], ingredients:[{n:"猪排骨",a:350,u:"g"},{n:"剁椒",a:100,u:"g",s:!0},{n:"蒜",a:4,u:"瓣"},{n:"姜",a:1,u:"块"},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"},{n:"葱",a:2,u:"根"}] },
  { id: 313, name: "酸汤鱼片",       cat: "荤", elements: ["riverFood","spicy","sourSweet","zingy"], tags: ["贵州","酸汤","开胃"], ingredients:[{n:"鱼片",a:300,u:"g"},{n:"番茄",a:2,u:"个"},{n:"酸菜",a:100,u:"g",s:!0},{n:"泡椒",a:5,u:"个",s:!0},{n:"木姜子油",a:1,u:"小勺",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"姜",a:1,u:"块"},{n:"葱",a:2,u:"根"}] },
  { id: 314, name: "火爆肥肠",       cat: "荤", elements: ["pork","spicy","stirFry","zingy"], tags: ["川味","火爆","下酒"], ingredients:[{n:"卤肥肠",a:300,u:"g"},{n:"干辣椒",a:10,u:"个"},{n:"花椒",a:1,u:"把",s:!0},{n:"青椒",a:2,u:"个"},{n:"洋葱",a:1,u:"个"},{n:"蒜",a:4,u:"瓣"},{n:"姜",a:1,u:"块"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0}] },
  { id: 315, name: "仔姜炒肉",       cat: "荤", elements: ["pork","stirFry","zingy","light"], tags: ["川味","仔姜","鲜辣"], ingredients:[{n:"猪瘦肉",a:250,u:"g"},{n:"仔姜",a:100,u:"g"},{n:"青椒",a:3,u:"个"},{n:"红椒",a:1,u:"个"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"}] },
  { id: 316, name: "鲜椒兔",         cat: "荤", elements: ["poultry","spicy","stirFry","zingy"], tags: ["四川","鲜辣","嫩滑"], ingredients:[{n:"兔肉",a:350,u:"g"},{n:"青椒",a:5,u:"个"},{n:"小米椒",a:6,u:"个"},{n:"鲜花椒",a:1,u:"把",s:!0},{n:"蒜",a:4,u:"瓣"},{n:"姜",a:1,u:"大块"},{n:"生抽",a:1,u:"勺"},{n:"料酒",a:1,u:"勺"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 317, name: "辣子田螺",       cat: "荤", elements: ["seafood","spicy","stirFry","dryPot"], tags: ["川味","麻辣","夜市"], ingredients:[{n:"田螺",a:500,u:"g"},{n:"干辣椒",a:15,u:"个"},{n:"花椒",a:1,u:"把",s:!0},{n:"郫县豆瓣酱",a:1.5,u:"勺",s:!0},{n:"蒜",a:6,u:"瓣"},{n:"姜",a:1,u:"大块"},{n:"葱",a:3,u:"根"},{n:"料酒",a:2,u:"勺"},{n:"白糖",a:1,u:"小勺"}] },
  { id: 318, name: "蒜香烤翅",       cat: "荤", elements: ["poultry","garlic","grill","light"], tags: ["烤箱","蒜香","少油"], ingredients:[{n:"鸡翅中",a:10,u:"个"},{n:"蒜",a:8,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"蜂蜜",a:1,u:"小勺",s:!0},{n:"料酒",a:1,u:"勺"},{n:"黑胡椒",a:1,u:"小勺"}] },
  { id: 319, name: "擂辣椒皮蛋",     cat: "荤", elements: ["egg","spicy","cold","zingy"], tags: ["湖南","擂菜","下饭"], ingredients:[{n:"皮蛋",a:3,u:"个",s:!0},{n:"青椒",a:5,u:"个"},{n:"蒜",a:4,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"醋",a:1,u:"小勺"},{n:"芝麻油",a:1,u:"小勺"}] },

  // ========== 素菜 ==========
  { id: 102, name: "手撕包菜",       cat: "素", elements: ["leafy","spicy","stirFry","sourSweet"], tags: ["湘菜","酸辣","下饭"], ingredients:[{n:"包菜",a:1,u:"个"},{n:"干辣椒",a:6,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"醋",a:1,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"猪油渣或五花肉",a:50,u:"g"}] },
  { id: 103, name: "蒜蓉空心菜",     cat: "素", elements: ["leafy","garlic","stirFry","light"], tags: ["家常","快手","清爽"], ingredients:[{n:"空心菜",a:300,u:"g"},{n:"蒜",a:5,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 104, name: "清炒上海青",     cat: "素", elements: ["leafy","garlic","stirFry","light"], tags: ["家常","简单","绿叶"], ingredients:[{n:"上海青",a:300,u:"g"},{n:"蒜",a:3,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 105, name: "白灼西兰花",     cat: "素", elements: ["leafy","blanch","light","garlic"], tags: ["粤式","白灼","健康"], ingredients:[{n:"西兰花",a:1,u:"颗"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"盐",a:1,u:"小勺"}] },
  { id: 106, name: "西红柿炒蛋",     cat: "素", elements: ["egg","sourSweet","melon","stirFry"], tags: ["家常","国民菜","酸甜"], ingredients:[{n:"番茄",a:2,u:"个"},{n:"鸡蛋",a:3,u:"个"},{n:"葱",a:1,u:"根"},{n:"白糖",a:1,u:"小勺"},{n:"盐",a:1,u:"小勺"}] },
  { id: 107, name: "酸辣土豆丝",     cat: "素", elements: ["root","spicy","sourSweet","stirFry"], tags: ["家常","酸辣","快手"], ingredients:[{n:"土豆",a:2,u:"个"},{n:"干辣椒",a:5,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"醋",a:1.5,u:"勺"},{n:"盐",a:1,u:"小勺"},{n:"蒜",a:2,u:"瓣"},{n:"葱",a:1,u:"根"}] },
  { id: 108, name: "蚝油生菜",       cat: "素", elements: ["leafy","blanch","light","umami"], tags: ["粤式","蚝油","快手"], ingredients:[{n:"生菜",a:300,u:"g"},{n:"蚝油",a:1.5,u:"勺",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"小勺"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 109, name: "麻婆豆腐(素)",   cat: "素", elements: ["tofu","spicy","sauce","garlic"], tags: ["四川","麻辣","下饭"], ingredients:[{n:"嫩豆腐",a:1,u:"块"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"花椒粉",a:1,u:"小勺",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"葱",a:2,u:"根"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 110, name: "地三鲜",         cat: "素", elements: ["root","grill","rich","garlic"], tags: ["东北","经典","下饭"], ingredients:[{n:"土豆",a:1,u:"个"},{n:"茄子",a:1,u:"个"},{n:"青椒",a:2,u:"个"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1.5,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"白糖",a:1,u:"小勺"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 111, name: "上汤娃娃菜",     cat: "素", elements: ["leafy","umami","light","steam"], tags: ["粤式","上汤","鲜甜"], ingredients:[{n:"娃娃菜",a:2,u:"颗"},{n:"皮蛋",a:1,u:"个",s:!0},{n:"火腿肠",a:1,u:"根"},{n:"蒜",a:3,u:"瓣"},{n:"高汤或浓汤宝",a:1,u:"块",s:!0}] },
  { id: 112, name: "清炒豆苗",       cat: "素", elements: ["leafy","light","stirFry","spring"], tags: ["粤式","时蔬","清爽"], ingredients:[{n:"豌豆苗",a:300,u:"g"},{n:"蒜",a:3,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"料酒",a:1,u:"小勺"}] },
  { id: 113, name: "番茄花菜",       cat: "素", elements: ["melon","sourSweet","stirFry","light"], tags: ["家常","酸甜","简单"], ingredients:[{n:"花菜",a:1,u:"颗"},{n:"番茄",a:2,u:"个"},{n:"蒜",a:2,u:"瓣"},{n:"番茄酱",a:1,u:"勺",s:!0},{n:"盐",a:1,u:"小勺"},{n:"白糖",a:1,u:"小勺"}] },
  { id: 114, name: "炒豆角",         cat: "素", elements: ["leafy","garlic","stirFry","light"], tags: ["家常","简单","炒时蔬"], ingredients:[{n:"豆角",a:300,u:"g"},{n:"蒜",a:3,u:"瓣"},{n:"干辣椒",a:3,u:"个"},{n:"生抽",a:1,u:"小勺"},{n:"盐",a:1,u:"小勺"}] },
  { id: 115, name: "清炒莴笋",       cat: "素", elements: ["root","light","stirFry","garlic"], tags: ["家常","清脆","简单"], ingredients:[{n:"莴笋",a:1,u:"根"},{n:"蒜",a:3,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 116, name: "鱼香茄子",       cat: "素", elements: ["root","sourSweet","spicy","stirFry"], tags: ["四川","鱼香","下饭"], ingredients:[{n:"茄子",a:2,u:"个"},{n:"蒜",a:4,u:"瓣"},{n:"姜",a:1,u:"小块"},{n:"泡椒",a:3,u:"个",s:!0},{n:"生抽",a:1,u:"勺"},{n:"醋",a:1,u:"勺"},{n:"白糖",a:1,u:"勺"},{n:"豆瓣酱",a:1,u:"小勺"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 118, name: "皮蛋豆腐",       cat: "素", elements: ["tofu","cold","light","summer"], tags: ["凉菜","简单","爽口"], ingredients:[{n:"内酯豆腐",a:1,u:"盒"},{n:"皮蛋",a:2,u:"个",s:!0},{n:"葱",a:2,u:"根"},{n:"生抽",a:1.5,u:"勺"},{n:"醋",a:1,u:"勺"},{n:"芝麻油",a:1,u:"小勺"},{n:"蒜",a:2,u:"瓣"}] },
  { id: 119, name: "蒜蓉粉丝蒸金针菇", cat: "素", elements: ["mushroom","garlic","steam","umami"], tags: ["粤式","蒜蓉","鲜美"], ingredients:[{n:"金针菇",a:200,u:"g"},{n:"龙口粉丝",a:1,u:"把"},{n:"蒜",a:8,u:"瓣"},{n:"蒸鱼豉油",a:2,u:"勺",s:!0},{n:"葱",a:2,u:"根"},{n:"小米椒",a:2,u:"个"}] },
  { id: 120, name: "香菇油菜",       cat: "素", elements: ["mushroom","leafy","stirFry","umami"], tags: ["家常","菌蔬","鲜美"], ingredients:[{n:"油菜",a:300,u:"g"},{n:"香菇",a:8,u:"个"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 121, name: "凉拌黄瓜",       cat: "素", elements: ["melon","cold","garlic","summer"], tags: ["凉菜","爽口","快手"], ingredients:[{n:"黄瓜",a:2,u:"根"},{n:"蒜",a:3,u:"瓣"},{n:"醋",a:1.5,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"芝麻油",a:1,u:"勺"},{n:"白糖",a:1,u:"小勺"},{n:"辣椒油",a:1,u:"勺"}] },
  { id: 122, name: "四喜烤麸",       cat: "素", elements: ["tofu","sauce","braise","sourSweet"], tags: ["上海","冷菜","甜咸"], ingredients:[{n:"烤麸",a:200,u:"g"},{n:"木耳",a:50,u:"g"},{n:"香菇",a:6,u:"个"},{n:"花生",a:50,u:"g"},{n:"黄花菜",a:30,u:"g"},{n:"生抽",a:2,u:"勺"},{n:"老抽",a:1,u:"勺"},{n:"白糖",a:2,u:"勺"}] },
  { id: 123, name: "素炒合菜",       cat: "素", elements: ["leafy","egg","stirFry","spring"], tags: ["北方","合炒","丰富"], ingredients:[{n:"韭菜",a:150,u:"g"},{n:"豆芽",a:150,u:"g"},{n:"鸡蛋",a:2,u:"个"},{n:"粉丝",a:1,u:"把"},{n:"生抽",a:1,u:"勺"},{n:"蒜",a:2,u:"瓣"}] },
  { id: 124, name: "韭菜炒豆芽",     cat: "素", elements: ["leafy","stirFry","spring","light"], tags: ["家常","快手","脆嫩"], ingredients:[{n:"韭菜",a:150,u:"g"},{n:"豆芽",a:200,u:"g"},{n:"蒜",a:2,u:"瓣"},{n:"生抽",a:1,u:"小勺"},{n:"盐",a:1,u:"小勺"}] },
  { id: 125, name: "干锅土豆片",     cat: "素", elements: ["root","spicy","dryPot","garlic"], tags: ["川味","干锅","下饭"], ingredients:[{n:"土豆",a:2,u:"个"},{n:"青椒",a:1,u:"个"},{n:"红椒",a:1,u:"个"},{n:"干辣椒",a:6,u:"个"},{n:"蒜",a:4,u:"瓣"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"生抽",a:1,u:"勺"}] },
  { id: 126, name: "腐竹炒木耳",     cat: "素", elements: ["tofu","mushroom","stirFry","light"], tags: ["家常","素食","丰富"], ingredients:[{n:"腐竹",a:100,u:"g"},{n:"木耳",a:50,u:"g"},{n:"胡萝卜",a:1,u:"根"},{n:"青椒",a:1,u:"个"},{n:"蒜",a:2,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0}] },
  { id: 127, name: "红烧冬瓜",       cat: "素", elements: ["melon","braise","sauce","light"], tags: ["家常","红烧","素肉"], ingredients:[{n:"冬瓜",a:500,u:"g"},{n:"生抽",a:1.5,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"白糖",a:1,u:"小勺"},{n:"蒜",a:3,u:"瓣"},{n:"葱",a:1,u:"根"}] },
  { id: 128, name: "炒藕片",         cat: "素", elements: ["root","stirFry","light","sourSweet"], tags: ["湖北","莲藕","脆甜"], ingredients:[{n:"莲藕",a:1,u:"节"},{n:"青椒",a:1,u:"个"},{n:"红椒",a:1,u:"个"},{n:"蒜",a:2,u:"瓣"},{n:"醋",a:1,u:"小勺"},{n:"白糖",a:1,u:"小勺"},{n:"盐",a:1,u:"小勺"}] },
  { id: 129, name: "蒜苗炒豆干",     cat: "素", elements: ["tofu","stirFry","garlic","light"], tags: ["家常","快手","豆香"], ingredients:[{n:"豆干",a:200,u:"g"},{n:"蒜苗",a:3,u:"根"},{n:"红椒",a:1,u:"个"},{n:"蒜",a:2,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"老抽",a:1,u:"小勺"}] },
  { id: 130, name: "芹菜炒香干",     cat: "素", elements: ["tofu","stirFry","light"], tags: ["家常","芹菜","豆干"], ingredients:[{n:"香干",a:200,u:"g"},{n:"芹菜",a:3,u:"根"},{n:"红椒",a:1,u:"个"},{n:"蒜",a:2,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"盐",a:1,u:"小勺"}] },
  { id: 131, name: "醋溜白菜",       cat: "素", elements: ["leafy","sourSweet","stirFry","spicy"], tags: ["北方","醋溜","开胃"], ingredients:[{n:"大白菜",a:300,u:"g"},{n:"干辣椒",a:4,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"醋",a:2,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"蒜",a:2,u:"瓣"}] },
  { id: 132, name: "白灼芥蓝",       cat: "素", elements: ["leafy","blanch","light","umami"], tags: ["粤式","白灼","脆嫩"], ingredients:[{n:"芥蓝",a:300,u:"g"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1.5,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"姜",a:1,u:"块"}] },
  { id: 133, name: "清炒丝瓜",       cat: "素", elements: ["melon","light","stirFry","summer"], tags: ["家常","清淡","清甜"], ingredients:[{n:"丝瓜",a:2,u:"根"},{n:"蒜",a:3,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 134, name: "蒜蓉蒸茄子",     cat: "素", elements: ["root","garlic","steam","light"], tags: ["家常","蒜蓉","软糯"], ingredients:[{n:"茄子",a:2,u:"个"},{n:"蒜",a:6,u:"瓣"},{n:"生抽",a:1.5,u:"勺"},{n:"醋",a:1,u:"勺"},{n:"芝麻油",a:1,u:"小勺"},{n:"葱",a:2,u:"根"}] },
  { id: 135, name: "菠菜拌粉丝",     cat: "素", elements: ["leafy","cold","light","garlic"], tags: ["凉菜","爽口","简单"], ingredients:[{n:"菠菜",a:250,u:"g"},{n:"粉丝",a:1,u:"把"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"醋",a:1,u:"勺"},{n:"芝麻油",a:1,u:"小勺"}] },
  { id: 136, name: "油炸花生米",     cat: "素", elements: ["root","grill"], tags: ["小食","下酒","香脆"], ingredients:[{n:"花生米",a:200,u:"g"},{n:"盐",a:1,u:"小勺"},{n:"油",a:3,u:"勺"}] },
  { id: 137, name: "西芹百合",       cat: "素", elements: ["root","stirFry","light","umami"], tags: ["粤式","清脆","清甜"], ingredients:[{n:"西芹",a:3,u:"根"},{n:"鲜百合",a:2,u:"个",s:!0},{n:"蒜",a:2,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 138, name: "红烧豆腐",       cat: "素", elements: ["tofu","braise","sauce","rich"], tags: ["家常","红烧","下饭"], ingredients:[{n:"老豆腐",a:1,u:"块"},{n:"青椒",a:1,u:"个"},{n:"红椒",a:1,u:"个"},{n:"生抽",a:1.5,u:"勺"},{n:"老抽",a:1,u:"小勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"葱",a:2,u:"根"},{n:"水淀粉",a:1,u:"勺",s:!0}] },
  { id: 139, name: "白灼秋葵",       cat: "素", elements: ["leafy","blanch","light","garlic"], tags: ["健康","白灼","粘滑"], ingredients:[{n:"秋葵",a:300,u:"g"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1.5,u:"勺"},{n:"蚝油",a:1,u:"勺",s:!0},{n:"小米椒",a:2,u:"个"}] },
  { id: 140, name: "炒三丝",         cat: "素", elements: ["root","stirFry","light","garlic"], tags: ["家常","什锦","快手"], ingredients:[{n:"土豆",a:1,u:"个"},{n:"胡萝卜",a:1,u:"根"},{n:"青椒",a:1,u:"个"},{n:"蒜",a:2,u:"瓣"},{n:"醋",a:1,u:"小勺"},{n:"盐",a:1,u:"小勺"}] },
  { id: 141, name: "榄菜四季豆",     cat: "素", elements: ["leafy","stirFry","garlic","rich"], tags: ["粤式","榄菜","下饭"], ingredients:[{n:"四季豆",a:300,u:"g"},{n:"橄榄菜",a:1.5,u:"勺",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"小勺"}] },
  { id: 142, name: "蒜蓉南瓜",       cat: "素", elements: ["melon","garlic","stirFry","autumn"], tags: ["家常","香甜","软糯"], ingredients:[{n:"南瓜",a:400,u:"g"},{n:"蒜",a:4,u:"瓣"},{n:"葱",a:1,u:"根"},{n:"盐",a:1,u:"小勺"}] },
  { id: 143, name: "净炒藕带",       cat: "素", elements: ["root","stirFry","light","summer"], tags: ["湖北","藕带","时令"], ingredients:[{n:"藕带",a:300,u:"g"},{n:"青椒",a:1,u:"个"},{n:"蒜",a:2,u:"瓣"},{n:"醋",a:1,u:"小勺"},{n:"盐",a:1,u:"小勺"}] },
  { id: 144, name: "蚝油杏鲍菇",     cat: "素", elements: ["mushroom","stirFry","umami","rich"], tags: ["菌菇","蚝油","素肉感"], ingredients:[{n:"杏鲍菇",a:3,u:"个"},{n:"青椒",a:1,u:"个"},{n:"蒜",a:3,u:"瓣"},{n:"蚝油",a:1.5,u:"勺",s:!0},{n:"生抽",a:1,u:"小勺"},{n:"老抽",a:1,u:"小勺"}] },
  { id: 145, name: "山药炒木耳",     cat: "素", elements: ["root","mushroom","stirFry","light"], tags: ["健康","清脆","黑白配"], ingredients:[{n:"山药",a:300,u:"g"},{n:"木耳",a:50,u:"g"},{n:"胡萝卜",a:1,u:"根"},{n:"蒜",a:2,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 146, name: "糖拌西红柿",     cat: "素", elements: ["melon","cold","sourSweet","summer"], tags: ["凉菜","童年味","解暑"], ingredients:[{n:"番茄",a:3,u:"个"},{n:"白糖",a:2,u:"勺"}] },
  { id: 147, name: "苦瓜炒蛋",       cat: "素", elements: ["egg","melon","stirFry","summer"], tags: ["清热","降火","健康"], ingredients:[{n:"苦瓜",a:1,u:"根"},{n:"鸡蛋",a:3,u:"个"},{n:"蒜",a:2,u:"瓣"},{n:"盐",a:1,u:"小勺"}] },
  { id: 148, name: "酱爆茄子",       cat: "素", elements: ["root","sauce","stirFry","rich"], tags: ["家常","酱香","下饭"], ingredients:[{n:"茄子",a:2,u:"个"},{n:"蒜",a:4,u:"瓣"},{n:"黄豆酱",a:1.5,u:"勺",s:!0},{n:"生抽",a:1,u:"勺"},{n:"白糖",a:1,u:"小勺"},{n:"青椒",a:1,u:"个"}] },
  { id: 149, name: "炒嫩南瓜丝",     cat: "素", elements: ["melon","stirFry","light","garlic"], tags: ["家常","清甜","快手"], ingredients:[{n:"嫩南瓜",a:300,u:"g"},{n:"蒜",a:2,u:"瓣"},{n:"盐",a:1,u:"小勺"}] },
  { id: 150, name: "葱油莴笋丝",     cat: "素", elements: ["root","cold","light","summer"], tags: ["凉菜","葱油","清脆"], ingredients:[{n:"莴笋",a:1,u:"根"},{n:"葱",a:3,u:"根"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0},{n:"芝麻油",a:1,u:"小勺"}] },
  { id: 151, name: "清炒芦笋",       cat: "素", elements: ["leafy","stirFry","light","spring"], tags: ["健康","芦笋","清脆"], ingredients:[{n:"芦笋",a:250,u:"g"},{n:"蒜",a:2,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"黑胡椒",a:1,u:"小勺"}] },
  { id: 153, name: "炝炒藕丁",       cat: "素", elements: ["root","spicy","stirFry","sourSweet"], tags: ["湖北","酸辣","脆爽"], ingredients:[{n:"莲藕",a:1,u:"节"},{n:"干辣椒",a:4,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"醋",a:1,u:"勺"},{n:"蒜",a:2,u:"瓣"},{n:"葱",a:1,u:"根"}] },
  { id: 154, name: "韭菜炒豆皮",     cat: "素", elements: ["leafy","tofu","stirFry","spring"], tags: ["家常","豆香","快手"], ingredients:[{n:"韭菜",a:150,u:"g"},{n:"豆腐皮",a:2,u:"张"},{n:"蒜",a:2,u:"瓣"},{n:"生抽",a:1,u:"小勺"},{n:"盐",a:1,u:"小勺"}] },
  { id: 155, name: "麻辣豆腐",       cat: "素", elements: ["tofu","spicy","sauce","stirFry"], tags: ["家常","麻辣","下饭"], ingredients:[{n:"老豆腐",a:1,u:"块"},{n:"干辣椒",a:4,u:"个"},{n:"花椒粉",a:1,u:"小勺",s:!0},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"蒜",a:2,u:"瓣"},{n:"葱",a:2,u:"根"}] },
  { id: 156, name: "蒸水蛋",         cat: "素", elements: ["egg","steam","light","umami"], tags: ["家常","嫩滑","简单"], ingredients:[{n:"鸡蛋",a:3,u:"个"},{n:"生抽",a:1,u:"勺"},{n:"芝麻油",a:1,u:"小勺"},{n:"葱",a:1,u:"根"}] },
  { id: 157, name: "虾皮蒸蛋",       cat: "素", elements: ["egg","seafood","steam","umami"], tags: ["家常","补钙","嫩滑"], ingredients:[{n:"鸡蛋",a:3,u:"个"},{n:"虾皮",a:15,u:"g"},{n:"生抽",a:1,u:"小勺"},{n:"葱",a:1,u:"根"},{n:"芝麻油",a:1,u:"小勺"}] },
  { id: 158, name: "凉拌木耳",       cat: "素", elements: ["mushroom","cold","garlic","sourSweet"], tags: ["凉菜","爽口","健康"], ingredients:[{n:"木耳",a:80,u:"g"},{n:"香菜",a:2,u:"根"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"醋",a:1,u:"勺"},{n:"辣椒油",a:1,u:"勺"},{n:"芝麻油",a:1,u:"小勺"},{n:"白糖",a:1,u:"小勺"}] },
  { id: 159, name: "干煸杏鲍菇",     cat: "素", elements: ["mushroom","spicy","stirFry","dryPot"], tags: ["川味","干煸","素肉感"], ingredients:[{n:"杏鲍菇",a:3,u:"个"},{n:"干辣椒",a:5,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"小勺"},{n:"孜然粉",a:1,u:"小勺"}] },
  { id: 160, name: "蒜蓉丝瓜",       cat: "素", elements: ["melon","garlic","steam","light"], tags: ["粤式","蒜蓉","清甜"], ingredients:[{n:"丝瓜",a:2,u:"根"},{n:"蒜",a:6,u:"瓣"},{n:"蒸鱼豉油",a:1,u:"勺",s:!0},{n:"粉丝",a:1,u:"把"}] },
  { id: 161, name: "拍黄瓜",         cat: "素", elements: ["melon","cold","garlic","summer"], tags: ["凉菜","快手","爽口"], ingredients:[{n:"黄瓜",a:2,u:"根"},{n:"蒜",a:4,u:"瓣"},{n:"醋",a:1,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"辣椒油",a:1,u:"勺"},{n:"芝麻油",a:1,u:"小勺"},{n:"白糖",a:1,u:"小勺"}] },
  { id: 162, name: "炒茼蒿",         cat: "素", elements: ["leafy","garlic","stirFry","light"], tags: ["家常","时蔬","简单"], ingredients:[{n:"茼蒿",a:300,u:"g"},{n:"蒜",a:4,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 163, name: "蜜汁山药",       cat: "素", elements: ["root","sourSweet","steam","light"], tags: ["甜品","滋补","甜香"], ingredients:[{n:"山药",a:300,u:"g"},{n:"蜂蜜",a:2,u:"勺",s:!0},{n:"枸杞",a:10,u:"个",s:!0}] },
  { id: 164, name: "剁椒金针菇",     cat: "素", elements: ["mushroom","spicy","steam","fermented"], tags: ["湖南","剁椒","快手"], ingredients:[{n:"金针菇",a:250,u:"g"},{n:"剁椒",a:2,u:"勺",s:!0},{n:"蒜",a:3,u:"瓣"},{n:"葱",a:2,u:"根"},{n:"蒸鱼豉油",a:1,u:"勺",s:!0}] },
  { id: 165, name: "凉拌腐竹",       cat: "素", elements: ["tofu","cold","garlic","summer"], tags: ["凉菜","豆制品","爽口"], ingredients:[{n:"腐竹",a:150,u:"g"},{n:"黄瓜",a:1,u:"根"},{n:"香菜",a:1,u:"根"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"醋",a:1,u:"勺"},{n:"辣椒油",a:1,u:"勺"},{n:"芝麻油",a:1,u:"小勺"}] },
  { id: 166, name: "清炒豌豆尖",     cat: "素", elements: ["leafy","light","stirFry","spring"], tags: ["四川","时蔬","嫩滑"], ingredients:[{n:"豌豆尖",a:300,u:"g"},{n:"蒜",a:3,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 167, name: "油焖笋",         cat: "素", elements: ["bamboo","braise","sauce","spring"], tags: ["江浙","时令","鲜美"], ingredients:[{n:"春笋",a:400,u:"g"},{n:"生抽",a:1.5,u:"勺"},{n:"老抽",a:1,u:"勺"},{n:"白糖",a:1.5,u:"勺"},{n:"料酒",a:1,u:"勺"},{n:"葱",a:2,u:"根"}] },
  { id: 168, name: "青椒土豆丝",     cat: "素", elements: ["root","stirFry","light","garlic"], tags: ["家常","经典","快手"], ingredients:[{n:"土豆",a:2,u:"个"},{n:"青椒",a:1,u:"个"},{n:"蒜",a:2,u:"瓣"},{n:"醋",a:1,u:"小勺"},{n:"盐",a:1,u:"小勺"}] },
  { id: 169, name: "泡椒藕带",       cat: "素", elements: ["root","spicy","fermented","summer"], tags: ["湖北","泡椒","酸辣"], ingredients:[{n:"藕带",a:250,u:"g"},{n:"泡椒",a:4,u:"个",s:!0},{n:"蒜",a:2,u:"瓣"},{n:"醋",a:1,u:"小勺"},{n:"盐",a:1,u:"小勺"}] },
  { id: 170, name: "地瓜叶炒蒜",     cat: "素", elements: ["leafy","garlic","stirFry","light"], tags: ["家常","时蔬","健康"], ingredients:[{n:"地瓜叶",a:300,u:"g"},{n:"蒜",a:4,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 171, name: "清炒茭瓜",       cat: "素", elements: ["melon","light","stirFry","garlic"], tags: ["家常","快手","清甜"], ingredients:[{n:"茭瓜",a:2,u:"根"},{n:"蒜",a:3,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 172, name: "清炒鸡毛菜",     cat: "素", elements: ["leafy","light","stirFry","garlic"], tags: ["家常","时蔬","快手"], ingredients:[{n:"鸡毛菜",a:300,u:"g"},{n:"蒜",a:3,u:"瓣"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 173, name: "蒜蓉粉丝蒸丝瓜", cat: "素", elements: ["melon","garlic","steam","light"], tags: ["粤式","蒜蓉","清甜"], ingredients:[{n:"丝瓜",a:2,u:"根"},{n:"龙口粉丝",a:1,u:"把"},{n:"蒜",a:6,u:"瓣"},{n:"蒸鱼豉油",a:1,u:"勺",s:!0},{n:"小米椒",a:1,u:"个"}] },
  { id: 174, name: "干锅花菜素",     cat: "素", elements: ["leafy","spicy","dryPot","garlic"], tags: ["川味","干锅","下饭"], ingredients:[{n:"花菜",a:300,u:"g"},{n:"干辣椒",a:5,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"蒜",a:4,u:"瓣"},{n:"郫县豆瓣酱",a:1,u:"勺",s:!0},{n:"生抽",a:1,u:"勺"},{n:"青椒",a:1,u:"个"}] },
  { id: 175, name: "酸辣藕丁",       cat: "素", elements: ["root","spicy","sourSweet","stirFry"], tags: ["湖北","酸辣","脆爽"], ingredients:[{n:"莲藕",a:1,u:"节"},{n:"干辣椒",a:5,u:"个"},{n:"花椒",a:1,u:"小把",s:!0},{n:"醋",a:1.5,u:"勺"},{n:"生抽",a:1,u:"小勺"},{n:"蒜",a:2,u:"瓣"},{n:"葱",a:1,u:"根"}] },
  { id: 176, name: "酸辣蕨根粉",     cat: "素", elements: ["cold","spicy","sourSweet","summer"], tags: ["凉菜","酸辣","解暑"], ingredients:[{n:"蕨根粉",a:150,u:"g"},{n:"黄瓜",a:1,u:"根"},{n:"香菜",a:2,u:"根"},{n:"蒜",a:3,u:"瓣"},{n:"醋",a:2,u:"勺"},{n:"生抽",a:1,u:"勺"},{n:"辣椒油",a:1.5,u:"勺"},{n:"白糖",a:1,u:"小勺"}] },
  { id: 177, name: "凉拌三丝",       cat: "素", elements: ["cold","light","summer","coolDown"], tags: ["凉菜","爽口","快手"], ingredients:[{n:"黄瓜",a:1,u:"根"},{n:"胡萝卜",a:1,u:"根"},{n:"粉丝",a:1,u:"把"},{n:"蒜",a:3,u:"瓣"},{n:"生抽",a:1,u:"勺"},{n:"醋",a:1,u:"勺"},{n:"芝麻油",a:1,u:"小勺"},{n:"辣椒油",a:1,u:"小勺"}] },
  { id: 178, name: "冰镇话梅番茄",   cat: "素", elements: ["cold","sourSweet","summer","coolDown"], tags: ["冰镇","话梅","甜品"], ingredients:[{n:"小番茄",a:300,u:"g"},{n:"话梅",a:6,u:"颗",s:!0},{n:"冰糖",a:30,u:"g"},{n:"柠檬",a:1,u:"个"}] },

  // ========== 汤 ==========
  { id: 201, name: "番茄蛋花汤",     cat: "汤", elements: ["egg","melon","sourSweet","light"], tags: ["家常","快手","酸甜"], ingredients:[{n:"番茄",a:2,u:"个"},{n:"鸡蛋",a:2,u:"个"},{n:"葱",a:1,u:"根"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0},{n:"芝麻油",a:1,u:"小勺"}] },
  { id: 202, name: "紫菜蛋花汤",     cat: "汤", elements: ["egg","seafood","light","umami"], tags: ["家常","快手","鲜美"], ingredients:[{n:"紫菜",a:1,u:"片",s:!0},{n:"鸡蛋",a:2,u:"个"},{n:"虾皮",a:10,u:"g"},{n:"葱",a:1,u:"根"},{n:"盐",a:1,u:"小勺"},{n:"芝麻油",a:1,u:"小勺"}] },
  { id: 203, name: "排骨藕汤",       cat: "汤", elements: ["pork","root","slowCook","winter"], tags: ["湖北","莲藕","滋补"], ingredients:[{n:"猪排骨",a:350,u:"g"},{n:"莲藕",a:1,u:"节"},{n:"姜",a:1,u:"块"},{n:"葱",a:2,u:"根"},{n:"盐",a:1.5,u:"小勺"},{n:"料酒",a:1,u:"勺"}] },
  { id: 204, name: "冬瓜排骨汤",     cat: "汤", elements: ["pork","melon","slowCook","summer"], tags: ["家常","清热","清淡"], ingredients:[{n:"猪排骨",a:300,u:"g"},{n:"冬瓜",a:400,u:"g"},{n:"姜",a:1,u:"块"},{n:"葱",a:1,u:"根"},{n:"盐",a:1.5,u:"小勺"},{n:"料酒",a:1,u:"勺"}] },
  { id: 205, name: "萝卜排骨汤",     cat: "汤", elements: ["pork","root","slowCook","winter"], tags: ["家常","萝卜","清甜"], ingredients:[{n:"猪排骨",a:300,u:"g"},{n:"白萝卜",a:1,u:"根"},{n:"姜",a:1,u:"块"},{n:"葱",a:1,u:"根"},{n:"盐",a:1.5,u:"小勺"},{n:"枸杞",a:10,u:"个",s:!0}] },
  { id: 206, name: "玉米排骨汤",     cat: "汤", elements: ["pork","slowCook","sourSweet","light"], tags: ["家常","玉米","清甜"], ingredients:[{n:"猪排骨",a:300,u:"g"},{n:"玉米",a:2,u:"根"},{n:"胡萝卜",a:1,u:"根"},{n:"姜",a:1,u:"块"},{n:"盐",a:1.5,u:"小勺"}] },
  { id: 207, name: "老母鸡汤",       cat: "汤", elements: ["poultry","slowCook","rich","winter"], tags: ["滋补","炖汤","暖心"], ingredients:[{n:"老母鸡",a:1,u:"只"},{n:"姜",a:1,u:"大块"},{n:"葱",a:3,u:"根"},{n:"枸杞",a:20,u:"个",s:!0},{n:"红枣",a:6,u:"个"},{n:"盐",a:2,u:"小勺"},{n:"料酒",a:2,u:"勺"}] },
  { id: 208, name: "酸辣汤",         cat: "汤", elements: ["egg","spicy","sourSweet","tofu"], tags: ["家常","酸辣","开胃"], ingredients:[{n:"鸡蛋",a:1,u:"个"},{n:"豆腐",a:1,u:"块"},{n:"木耳",a:30,u:"g"},{n:"金针菇",a:100,u:"g"},{n:"醋",a:2,u:"勺"},{n:"白胡椒粉",a:1,u:"小勺"},{n:"水淀粉",a:1.5,u:"勺",s:!0},{n:"芝麻油",a:1,u:"小勺"}] },
  { id: 209, name: "山药排骨汤",     cat: "汤", elements: ["pork","root","slowCook","autumn"], tags: ["滋补","山药","健脾"], ingredients:[{n:"猪排骨",a:300,u:"g"},{n:"山药",a:300,u:"g"},{n:"胡萝卜",a:1,u:"根"},{n:"姜",a:1,u:"块"},{n:"盐",a:1.5,u:"小勺"},{n:"枸杞",a:10,u:"个",s:!0}] },
  { id: 210, name: "鲫鱼豆腐汤",     cat: "汤", elements: ["riverFood","tofu","slowCook","light"], tags: ["家常","奶白","鲜美"], ingredients:[{n:"鲫鱼",a:1,u:"条"},{n:"嫩豆腐",a:1,u:"块"},{n:"姜",a:1,u:"块"},{n:"葱",a:2,u:"根"},{n:"盐",a:1.5,u:"小勺"},{n:"料酒",a:1,u:"勺"},{n:"白胡椒粉",a:1,u:"小勺"}] },
  { id: 211, name: "豆腐青菜汤",     cat: "汤", elements: ["tofu","leafy","light","blanch"], tags: ["家常","清淡","快手"], ingredients:[{n:"嫩豆腐",a:1,u:"块"},{n:"小油菜",a:2,u:"棵"},{n:"葱",a:1,u:"根"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0},{n:"芝麻油",a:1,u:"小勺"}] },
  { id: 212, name: "冬瓜海带汤",     cat: "汤", elements: ["melon","seafood","light","summer"], tags: ["清热","解暑","清淡"], ingredients:[{n:"冬瓜",a:300,u:"g"},{n:"海带",a:100,u:"g"},{n:"姜",a:1,u:"块"},{n:"葱",a:1,u:"根"},{n:"盐",a:1,u:"小勺"},{n:"虾皮",a:10,u:"g"}] },
  { id: 213, name: "鸡蛋羹",         cat: "汤", elements: ["egg","steam","light","umami"], tags: ["家常","嫩滑","简单"], ingredients:[{n:"鸡蛋",a:3,u:"个"},{n:"生抽",a:1,u:"勺"},{n:"芝麻油",a:1,u:"小勺"},{n:"葱",a:1,u:"根"},{n:"温水",a:200,u:"ml"}] },
  { id: 214, name: "菌菇汤",         cat: "汤", elements: ["mushroom","slowCook","light","umami"], tags: ["素食","鲜美","健康"], ingredients:[{n:"香菇",a:6,u:"个"},{n:"金针菇",a:100,u:"g"},{n:"杏鲍菇",a:1,u:"个"},{n:"葱",a:1,u:"根"},{n:"姜",a:1,u:"块"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 215, name: "牛肉萝卜汤",     cat: "汤", elements: ["beefLamb","root","slowCook","winter"], tags: ["滋补","暖身","清甜"], ingredients:[{n:"牛腩",a:300,u:"g"},{n:"白萝卜",a:1,u:"根"},{n:"姜",a:1,u:"大块"},{n:"葱",a:2,u:"根"},{n:"盐",a:1.5,u:"小勺"},{n:"料酒",a:2,u:"勺"},{n:"八角",a:1,u:"个"}] },
  { id: 216, name: "鱼头豆腐汤",     cat: "汤", elements: ["riverFood","tofu","slowCook","umami"], tags: ["家常","奶白","鲜美"], ingredients:[{n:"鱼头",a:1,u:"个"},{n:"嫩豆腐",a:1,u:"块"},{n:"姜",a:1,u:"大块"},{n:"葱",a:2,u:"根"},{n:"盐",a:1.5,u:"小勺"},{n:"料酒",a:2,u:"勺"},{n:"白胡椒粉",a:1,u:"小勺"}] },
  { id: 217, name: "菠菜蛋花汤",     cat: "汤", elements: ["egg","leafy","light","stirFry"], tags: ["家常","快手","营养"], ingredients:[{n:"菠菜",a:150,u:"g"},{n:"鸡蛋",a:2,u:"个"},{n:"葱",a:1,u:"根"},{n:"盐",a:1,u:"小勺"},{n:"芝麻油",a:1,u:"小勺"}] },
  { id: 218, name: "酸梅汤",         cat: "汤", elements: ["sourSweet","cold","summer","melon"], tags: ["饮品","解暑","开胃"], ingredients:[{n:"乌梅",a:30,u:"g",s:!0},{n:"山楂",a:20,u:"g",s:!0},{n:"甘草",a:5,u:"g",s:!0},{n:"桂花",a:1,u:"小勺",s:!0},{n:"冰糖",a:80,u:"g"}] },
  { id: 219, name: "虾仁冬瓜汤",     cat: "汤", elements: ["seafood","melon","light","summer"], tags: ["海鲜","清淡","清甜"], ingredients:[{n:"虾仁",a:150,u:"g"},{n:"冬瓜",a:300,u:"g"},{n:"姜",a:1,u:"块"},{n:"葱",a:1,u:"根"},{n:"盐",a:1,u:"小勺"},{n:"料酒",a:1,u:"小勺"}] },
  { id: 220, name: "莲藕排骨汤",     cat: "汤", elements: ["pork","root","slowCook","autumn"], tags: ["湖北","莲藕","粉糯"], ingredients:[{n:"猪排骨",a:350,u:"g"},{n:"莲藕",a:2,u:"节"},{n:"姜",a:1,u:"大块"},{n:"葱",a:2,u:"根"},{n:"盐",a:1.5,u:"小勺"},{n:"花椒",a:10,u:"粒"}] },
  { id: 221, name: "鸭子汤",         cat: "汤", elements: ["poultry","slowCook","rich","winter"], tags: ["滋补","老鸭","清润"], ingredients:[{n:"鸭肉",a:500,u:"g"},{n:"冬瓜",a:300,u:"g"},{n:"薏米",a:30,u:"g",s:!0},{n:"姜",a:1,u:"大块"},{n:"葱",a:2,u:"根"},{n:"盐",a:2,u:"小勺"},{n:"料酒",a:2,u:"勺"}] },
  { id: 222, name: "绿豆汤",         cat: "汤", elements: ["light","cold","summer","melon"], tags: ["解暑","甜品","清热"], ingredients:[{n:"绿豆",a:150,u:"g"},{n:"冰糖",a:50,u:"g"},{n:"百合",a:20,u:"g",s:!0}] },
  { id: 223, name: "海带排骨汤",     cat: "汤", elements: ["pork","seafood","slowCook","light"], tags: ["家常","海带","补碘"], ingredients:[{n:"猪排骨",a:300,u:"g"},{n:"海带结",a:150,u:"g"},{n:"姜",a:1,u:"块"},{n:"葱",a:1,u:"根"},{n:"盐",a:1.5,u:"小勺"},{n:"料酒",a:1,u:"勺"}] },
  { id: 224, name: "银耳莲子羹",     cat: "汤", elements: ["slowCook","sourSweet","light"], tags: ["甜品","银耳","润肺"], ingredients:[{n:"银耳",a:1,u:"朵",s:!0},{n:"莲子",a:30,u:"g",s:!0},{n:"红枣",a:8,u:"个"},{n:"冰糖",a:40,u:"g"},{n:"枸杞",a:15,u:"个",s:!0}] },
  { id: 225, name: "三鲜汤",         cat: "汤", elements: ["seafood","egg","umami","light"], tags: ["家常","鲜美","快手"], ingredients:[{n:"虾仁",a:100,u:"g"},{n:"木耳",a:30,u:"g"},{n:"鸡蛋",a:1,u:"个"},{n:"火腿肠",a:1,u:"根"},{n:"青菜",a:2,u:"棵"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 226, name: "番茄菌菇汤",     cat: "汤", elements: ["melon","mushroom","sourSweet","light"], tags: ["家常","酸甜","鲜美"], ingredients:[{n:"番茄",a:2,u:"个"},{n:"金针菇",a:100,u:"g"},{n:"香菇",a:4,u:"个"},{n:"葱",a:1,u:"根"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 227, name: "丝瓜蛋花汤",     cat: "汤", elements: ["egg","melon","light","summer"], tags: ["家常","快手","清甜"], ingredients:[{n:"丝瓜",a:1,u:"根"},{n:"鸡蛋",a:2,u:"个"},{n:"葱",a:1,u:"根"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 228, name: "酸辣鱼片汤",     cat: "汤", elements: ["riverFood","spicy","sourSweet","rich"], tags: ["川味","酸辣","开胃"], ingredients:[{n:"鱼片",a:200,u:"g"},{n:"番茄",a:2,u:"个"},{n:"泡椒",a:3,u:"个",s:!0},{n:"白醋",a:1,u:"勺"},{n:"白胡椒粉",a:1,u:"小勺"},{n:"姜",a:1,u:"块"},{n:"蒜",a:2,u:"瓣"},{n:"葱",a:1,u:"根"}] },
  { id: 229, name: "萝卜丝鲫鱼汤",   cat: "汤", elements: ["riverFood","root","slowCook","light"], tags: ["家常","奶白","鲜甜"], ingredients:[{n:"鲫鱼",a:1,u:"条"},{n:"白萝卜",a:1,u:"根"},{n:"姜",a:1,u:"块"},{n:"葱",a:2,u:"根"},{n:"盐",a:1.5,u:"小勺"},{n:"料酒",a:1,u:"勺"}] },
  { id: 230, name: "金汤肥牛汤",     cat: "汤", elements: ["beefLamb","spicy","sourSweet","rich"], tags: ["川味","金汤","酸辣"], ingredients:[{n:"肥牛卷",a:250,u:"g"},{n:"金针菇",a:150,u:"g"},{n:"泡椒",a:5,u:"个",s:!0},{n:"黄灯笼椒酱",a:1,u:"勺",s:!0},{n:"白醋",a:1.5,u:"勺"},{n:"蒜",a:3,u:"瓣"},{n:"姜",a:1,u:"块"}] },
  { id: 231, name: "豆腐海带汤",     cat: "汤", elements: ["tofu","seafood","light","summer"], tags: ["素食","清淡","健康"], ingredients:[{n:"嫩豆腐",a:1,u:"块"},{n:"海带",a:100,u:"g"},{n:"葱",a:1,u:"根"},{n:"盐",a:1,u:"小勺"},{n:"芝麻油",a:1,u:"小勺"}] },
  { id: 232, name: "玉米羹",         cat: "汤", elements: ["egg","sourSweet","slowCook","light"], tags: ["粤式","羹汤","清甜"], ingredients:[{n:"玉米粒",a:200,u:"g"},{n:"鸡蛋",a:1,u:"个"},{n:"水淀粉",a:1.5,u:"勺",s:!0},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 233, name: "花生猪蹄汤",     cat: "汤", elements: ["pork","slowCook","rich","winter"], tags: ["滋补","猪蹄","胶原"], ingredients:[{n:"猪蹄",a:1,u:"只"},{n:"花生",a:80,u:"g"},{n:"姜",a:1,u:"大块"},{n:"料酒",a:2,u:"勺"},{n:"盐",a:1.5,u:"小勺"},{n:"红枣",a:5,u:"个"}] },
  { id: 234, name: "黄瓜皮蛋汤",     cat: "汤", elements: ["melon","egg","light","summer"], tags: ["家常","快手","清热"], ingredients:[{n:"黄瓜",a:1,u:"根"},{n:"皮蛋",a:2,u:"个",s:!0},{n:"葱",a:1,u:"根"},{n:"姜",a:1,u:"小块"},{n:"盐",a:1,u:"小勺"},{n:"鸡精",a:1,u:"小勺",s:!0}] },
  { id: 235, name: "莲藕花生汤",     cat: "汤", elements: ["root","slowCook","light","autumn"], tags: ["素食","莲藕","粉糯"], ingredients:[{n:"莲藕",a:2,u:"节"},{n:"花生",a:80,u:"g"},{n:"红枣",a:6,u:"个"},{n:"姜",a:1,u:"块"},{n:"盐",a:1.5,u:"小勺"}] },
  { id: 236, name: "花蛤冬瓜汤",     cat: "汤", elements: ["seafood","melon","light","summer"], tags: ["海鲜","清淡","清热"], ingredients:[{n:"花蛤",a:300,u:"g"},{n:"冬瓜",a:300,u:"g"},{n:"姜",a:1,u:"块"},{n:"葱",a:1,u:"根"},{n:"盐",a:1,u:"小勺"},{n:"料酒",a:1,u:"小勺"},{n:"芝麻油",a:1,u:"小勺"}] },
  { id: 237, name: "菌菇鸡汤",       cat: "汤", elements: ["poultry","mushroom","slowCook","umami"], tags: ["滋补","菌菇","鲜美"], ingredients:[{n:"鸡",a:1,u:"只"},{n:"香菇",a:8,u:"个"},{n:"杏鲍菇",a:2,u:"个"},{n:"红枣",a:6,u:"个"},{n:"枸杞",a:15,u:"个",s:!0},{n:"姜",a:1,u:"大块"},{n:"盐",a:2,u:"小勺"},{n:"料酒",a:2,u:"勺"}] },
  { id: 238, name: "番茄牛肉汤",     cat: "汤", elements: ["beefLamb","sourSweet","slowCook","rich"], tags: ["家常","酸甜","浓郁"], ingredients:[{n:"牛腩",a:250,u:"g"},{n:"番茄",a:3,u:"个"},{n:"土豆",a:1,u:"个"},{n:"洋葱",a:1,u:"个"},{n:"番茄酱",a:1,u:"勺",s:!0},{n:"姜",a:1,u:"块"},{n:"盐",a:1.5,u:"小勺"},{n:"料酒",a:1,u:"勺"}] },
  { id: 239, name: "冬瓜老鸭汤",     cat: "汤", elements: ["poultry","melon","slowCook","summer"], tags: ["滋补","清热","老火"], ingredients:[{n:"鸭肉",a:400,u:"g"},{n:"冬瓜",a:400,u:"g"},{n:"薏米",a:30,u:"g",s:!0},{n:"姜",a:1,u:"大块"},{n:"葱",a:2,u:"根"},{n:"盐",a:2,u:"小勺"},{n:"料酒",a:2,u:"勺"}] },
  { id: 240, name: "猪肚鸡汤",       cat: "汤", elements: ["pork","poultry","slowCook","rich"], tags: ["粤式","滋补","奶白"], ingredients:[{n:"猪肚",a:1,u:"个"},{n:"鸡",a:1,u:"只"},{n:"白胡椒粒",a:10,u:"粒"},{n:"姜",a:1,u:"大块"},{n:"枸杞",a:15,u:"个",s:!0},{n:"盐",a:2,u:"小勺"},{n:"料酒",a:2,u:"勺"}] },
  { id: 241, name: "酸辣海鲜汤",     cat: "汤", elements: ["seafood","spicy","sourSweet","tropical"], tags: ["泰式","酸辣","开胃"], ingredients:[{n:"虾仁",a:150,u:"g"},{n:"鱿鱼",a:100,u:"g"},{n:"花蛤",a:150,u:"g"},{n:"番茄",a:2,u:"个"},{n:"柠檬",a:1,u:"个"},{n:"小米椒",a:4,u:"个"},{n:"香菜",a:2,u:"根"},{n:"鱼露",a:1,u:"勺",s:!0},{n:"椰浆",a:100,u:"ml",s:!0}] },
  { id: 242, name: "绿豆汤",         cat: "汤", elements: ["coolDown","summer","light","cold"], tags: ["解暑","经典","清凉"], ingredients:[{n:"绿豆",a:200,u:"g"},{n:"冰糖",a:60,u:"g"},{n:"百合",a:20,u:"g",s:!0}] },
  { id: 243, name: "绿豆百合汤",     cat: "汤", elements: ["coolDown","summer","light","moisten"], tags: ["解暑","百合","润肺"], ingredients:[{n:"绿豆",a:150,u:"g"},{n:"百合",a:30,u:"g",s:!0},{n:"冰糖",a:50,u:"g"},{n:"莲子",a:20,u:"g",s:!0}] },
  { id: 244, name: "银耳雪梨羹",     cat: "汤", elements: ["moisten","autumn","sourSweet","light"], tags: ["润肺","雪梨","清甜"], ingredients:[{n:"银耳",a:1,u:"朵",s:!0},{n:"雪梨",a:2,u:"个"},{n:"红枣",a:6,u:"个"},{n:"冰糖",a:40,u:"g"},{n:"枸杞",a:15,u:"个",s:!0}] },
  { id: 245, name: "冬瓜薏米汤",     cat: "汤", elements: ["coolDown","summer","melon","light"], tags: ["祛湿","清热","清淡"], ingredients:[{n:"冬瓜",a:400,u:"g"},{n:"薏米",a:40,u:"g",s:!0},{n:"姜",a:1,u:"块"},{n:"盐",a:1,u:"小勺"},{n:"葱",a:1,u:"根"}] },
  { id: 246, name: "苦瓜排骨汤",     cat: "汤", elements: ["coolDown","summer","pork","light"], tags: ["清热","降火","夏日"], ingredients:[{n:"猪排骨",a:300,u:"g"},{n:"苦瓜",a:1,u:"根"},{n:"黄豆",a:50,u:"g"},{n:"姜",a:1,u:"块"},{n:"盐",a:1.5,u:"小勺"},{n:"料酒",a:1,u:"勺"}] },
];

// 导出 (用于 module 环境)
if (typeof module !== "undefined" && module.exports) {
  module.exports = { ELEMENTS, SCENARIO_WORDS, RECIPES };
}
